project:
  type: website

website:
  page-navigation: true
  title: "MATH 4780 (MSSC 5780) - Fall 2026"
  description: "Homepage for MATH 4780 (MSSC 5780) - Statistical Methods at Marquette University, Fall 2026."
  site-url: "https://math4780-f26.github.io/website/"

  repo-url: https://github.com/math4780-f26/website
  repo-actions: [edit, issue]

  open-graph: true

  # twitter-card:
  #   creator: "@minebocek"
  #   image: "images/twitter-card.png"

  page-footer:
    right: 'This page is built with ❤️ and [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2026, Cheng-Han Yu"
    background: "#b5e2ff"

  sidebar:
    background: "#b5e2ff"
    logo: "/images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/math4780-f26/website
        text: "GitHub organization"
      # - icon: code-square
      #   href: https://cmgr.oit.duke.edu/containers
      #   text: "RStudio Containers"
      - icon: person-fill
        href: https://d2l.mu.edu/d2l/home/630388
        text: "D2L"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          # - href: course-news.qmd
          #   text: News/Annoucements
          - href: course-overview.qmd
            text: Overview
          - href: index.qmd
            text: Schedule
          - href: course-syllabus.qmd
            text: Syllabus
          # - href: course-hours.qmd
          #   text: Help Desk Hours

          # - href: course-support.qmd
          #   text: Support
          # - href: course-team.qmd
          #   text: Teaching team

          # - href: course-links.qmd
          #   text: Useful links
          # - href: course-faq.qmd
          #   text: FAQ
      # - section: "Computing"
      #   contents:
      #     - href: computing-access.qmd
      #       text: Access
      #     - href: computing-troubleshooting.qmd
      #       text: Troubleshooting

      # - section: "Midterm Project I"
      #   contents:
      #     - href: present-description.qmd
      #       text: Guideline and Policy
      #     - href: present-work.qmd
      #       text: Topics and Works
      # - section: "Midterm Project II"
      #   contents:
      #     - href: present-description-2.qmd
      #       text: Guideline and Policy
      #     - href: present-work-2.qmd
      #       text: Topics and Works
      # - section: "Final Project"
      #   contents:
      #     - href: project-description.qmd
      #       text: Guideline and Policy
      #     # - href: project-description-5780.qmd
      #     #   text: Guideline for MATH 5780
      #     - href: project-work.qmd
      #       text: Topics and Works
      - hw.qmd
      # - ws.qmd
      # - exercise.qmd
      # - exam.qmd
      # - project/project.qmd
      - section: "Class Activities"
        contents:
          - href: activity-description_new.qmd
            text: Description
          - href: activity-work_new.qmd
            text: Activity work

      - section: "Project"
        contents:
          - href: project-description-4780_new.qmd
            text: Guideline for MATH 4780
          - href: project-description-5780_new.qmd
            text: Guideline for MATH 5780
          - href: project-work_new.qmd
            text: Project Group and Proposal
      # - project/projet.qmd
      # - ae.qmd
      # - exam-review.qmd
      - section: "Supplementary material for MSSC 5780"
        contents:
          # - href: supplemental/slr-derivations.qmd
          #   text: SLR derivations
          - href: supplemental/model-diagnostics-matrix.qmd
            text: Model diagnostics
          - href: supplemental/mlr-matrix.qmd
            text: MLR matrix notation
          - href: supplemental/log-transformations.qmd
            text: Log transformations
          - href: supplemental/model-selection-criteria.qmd
            text: Model selection criteria

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Atkinson Hyperlegible
    code-copy: hover
    code-link: true
    code-overflow: wrap
    toc: true
    highlight-style: a11y-light

execute:
  freeze: auto

editor: source