---
title: "Take-home Exam 1"
subtitle: "Take-home Exam for Week 1 to 7"
categories: "Exam"
format:
  html:
    html-math-method: mathjax
editor: source
execute: 
  include: false
---

::: callout-important
[Due **Friday, March 6, 11:59 PM**]{.red}
:::

- Please submit your work in *one* **PDF** file to **D2L > Assessments > Dropbox**. Multiple files or a file that is not in pdf format is not allowed. 

- By writing your name and student ID on this exam, you commit to academic integrity through the following honor pledge:

> I recognize the importance of personal integrity in all aspects of life and work. I commit myself to truthfulness, honor and responsibility, by which I earn the respect of others. I support the development of good character and commit myself to uphold the highest standards of academic integrity as an important aspect of personal integrity. My commitment obliges me to conduct myself according to the Marquette University Honor Code.

- [**_This exam is to be entirely your own efforts._**]{.red} You may use any resources, including Generative AI tools, while working on this exam. However, **you are NOT allowed to discuss the exam with anyone except Dr. Yu, nor may you post any of the exam questions on any platform to solicit answers.** Any violation of this policy will be treated as academic misconduct. If you are caught cheating, your case will be reported immediately to the Academic Integrity Council.

- In your exam, please number problems/questions in order.

- Even if you use R to compute your final answer, you must show your calculation steps and/or explain your reasoning in order to receive full credit.

- **Handwritten tables and figures receive no credits**.

<!-- - You do not need to attach your code of any language you use in the homework. However, if you fail to complete your calculations or produce your table or figure, you receive partial credits if your code is attached. -->

<!-- - Questions started with **(MSSC)** are required for MSSC 5720 students, and optional for MATH 4720 students. -->

# Exam Problems (20 points)

<!-- (@) **Normal Approximation to Binomial**. Suppose that 60\% of Americans have had chickenpox by the time they reach adulthood. -->
<!--   (a) Suppose we take a random sample of 6 American adults.  Let $X$ be the number of people out of the 6 who had chickenpox during childhood. If $X \sim binomial(n, \pi)$, determine the value of $n$ and $\pi$. -->

<!--   (b) With (a), compute the probability that **at least** 3 adults have had chickenpox. -->

<!--   (c) With (a), what is the value of the mean $\mu$ and variance $\sigma^2$ of $X \sim binomial(n, \pi)$? -->

<!--   (d) Now treat $X$ as a normal random variable, i.e., $X \sim N(\mu, \sigma^2)$, where $\mu$ and $\sigma^2$ are the values obtained in (c). Compute the probability that **at least** 3 adults have had chickenpox. -->

<!--   (e) Suppose now we take a random sample of 60 American adults. Using $binomial(n, \pi)$ and $N(\mu, \sigma^2)$ with new parameter values $n$, $\mu$, and $\sigma^2$ to compute the probability that **at least** 30 adults have had chickenpox. -->

<!--   (f) Compare binomial and normal probabilities when sample size are 6 and 60. In which case,  binomial and normal probabilities are closer? -->

<!--   (g) **(MSSC)** Is there any issue when we use a normal distribution to approximate a binomial distribution? Use [*continuity correction*](https://chenghanyu-introstatsbook.netlify.app/prob-cont#normal-approximation-to-binomial-distribution) on (e). Do you get a better approximation result? -->

<!-- ```{r} -->
<!-- ## 1 -->
<!-- # (a) -->
<!-- n <- 6; p <- 0.6 -->

<!-- ## (b) -->
<!-- 1 - pbinom(q = 2, size = n, prob = p) -->

<!-- ## (c) -->
<!-- (mu <- n*p) -->
<!-- (var <- n*p*(1-p)) -->

<!-- ## (d) -->
<!-- 1 - pnorm(q = 3, mean = mu, sd = sqrt(var)) -->

<!-- ## (e) -->
<!-- n <- 60 -->
<!-- (mu <- n*p) -->
<!-- (var <- n*p*(1-p)) -->
<!-- 1 - pbinom(q = 29, size = n, prob = p) -->
<!-- 1 - pnorm(q = 30, mean = mu, sd = sqrt(var)) -->

<!-- ## (f) -->
<!-- # When n = 60 -->

<!-- ## (g) -->
<!-- 1 - pnorm(q = 29.5, mean = mu, sd = sqrt(var)) -->
<!-- ``` -->

<!-- <br> -->

(@) The following body masses (in grams) of 50 wintering birds were reported in the paper ``*Temperature and the Northern Distributions of Wintering Birds*,'' by Richard Repasky (1991). The data are provided in [exam1data.csv](./exam1data.csv). First download and upload the data to your Posit Cloud (RStudio). Then import the data using the command

>  `data <- read.csv("./exam1data.csv")`

where `"./exam1data.csv"` is the file path and `./` means your current working directory.



  (a) Make a histogram of `bodymass`.
    
  (b) Construct a boxplot with label X-axis or Y-axis (depending on whether the plot is horizontal or vertical) as `Body Mass (in grams)` with a title `Boxplot of Body Mass (g)`. 
  
  * Are there any outliers in the data set? If yes, identify them.
  * Comment the skewness of the data, and which should be a better measure of center.
  
  (c) In context, state what population parameter $\mu$ you are estimating.
  
  (d) Construct a 95\% Student-$t$ confidence interval for the population mean body mass $\mu$. Report the interval and interpret it in context.
  
  (e) Remove the outliers you identified earlier in the descriptive statistics problem and recompute the 95\% Student-$t$ confidence interval for $\mu$. Compare the two intervals (center and width). Briefly explain why they differ.
  
  <!-- (c) Find 30-th, 60-th and 90-th percentiles (or 0.3, 0.6 and 0.9 quantiles) as wells as the sample mean and median. Based on (a), (b),  and (c), comment the skewness of the data, and which should be a better measure of center. -->

<!-- Many statistical methods assume data are normally distributed, and the [*Quantile-Quantile plot* or *QQ plot*](https://chenghanyu-introstatsbook.netlify.app/prob-cont#checking-normality) helps us check the normality assumption. If the data are approximately normally distributed, the points on the QQ plot will lie close to a straight line. -->

<!--   (d) Remove the outliers you identified in (b) and construct a QQ-plot for the data by using the functions `qqnorm()` and `qqline()`. Does the distribution without outliers look like normal? Please comment. -->

<!--   (e) Transform the data with outliers removed by taking the natural log with base $e = 2.71828...$. Construct a QQ-plot for the transformed data and comment on its normality. -->
	



<br>

(@) **AI Usage Declaration.** Using GenAI is permitted for this course. If you choose to use GenAI to assist with your exam, you must include a brief statement documenting your use. Please provide the following information:

  (a) **Why/How I Used AI** Why do you need to use GenAI? Which tool did you use? Describe your prompts or questions. What and how did you ask the AI to help you?
    
  (b) **Generated Output** Include a screenshot or excerpt (copy and paste) of the AI’s response.
    
  (c) **How I Used the Output** Did you revise it? Did you use it directly, or compare it with your answers? What decisions did you make based on the output?


	 
<!--   An alternative is to enter all data values by yourself: -->

<!-- 	  7.7    10.1    21.6     8.6    12.0    11.4    16.6     9.4 -->
<!-- 	 11.5     9.0     8.2    20.2    48.5    21.6    26.1     6.2 -->
<!-- 	 19.1    21.0    28.1    10.6    31.6     6.7     5.0    68.8 -->
<!-- 	 23.9    19.8    20.1     6.0    99.6    19.8    16.5     9.0 -->
<!-- 	448.0    21.3    17.4    36.9    34.0    41.0    15.9    12.5 -->
<!-- 	 10.2    31.0    21.5    11.9    32.5     9.8    93.9    10.9 -->
<!-- 	 19.6    14.5 -->


```{r}
data <- read.csv("./exam1data.csv")
data <- data$bodymass
par(mar = c(4, 4, 2, 0))
## (a)
hist(data, breaks = 30)

## (b)
boxplot(data, horizontal = TRUE, xlab = "Body Mass (in grams)", 
        main = "Boxplot of Body Mass (g)")

(outliers <- sort(data, decreasing = TRUE)[1:4])

## (c)
quantile(data, probs = c(0.3, 0.6, 0.9))
mean(data)
sd(data)
## right-skewed. Median is better

## (d)
data_remove <- data[-which(data %in% outliers)]
qqnorm(data_remove, main = "Normal Quantile Plot: Body Mass without Outliers")
qqline(data_remove)
## not normal. still right-skewed

## (e)
qqnorm(log(data_remove), 
       main = "Normal Quantile Plot: Log of Body Mass without Outliers")
qqline(log(data_remove))
## look more like normal after log transformation
```

