{
  "hash": "e0866aef05e54b058aeca6e190c7f249",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Inference for Categorical Data `<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 640 512\" style=\"height:1em;width:1.25em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;\"><path d=\"M64 64a64 64 0 1 1 128 0A64 64 0 1 1 64 64zM25.9 233.4C29.3 191.9 64 160 105.6 160h44.8c27 0 51 13.4 65.5 34.1c-2.7 1.9-5.2 4-7.5 6.3l-64 64c-21.9 21.9-21.9 57.3 0 79.2L192 391.2V464c0 26.5-21.5 48-48 48H112c-26.5 0-48-21.5-48-48V348.3c-26.5-9.5-44.7-35.8-42.2-65.6l4.1-49.3zM448 64a64 64 0 1 1 128 0A64 64 0 1 1 448 64zM431.6 200.4c-2.3-2.3-4.9-4.4-7.5-6.3c14.5-20.7 38.6-34.1 65.5-34.1h44.8c41.6 0 76.3 31.9 79.7 73.4l4.1 49.3c2.5 29.8-15.7 56.1-42.2 65.6V464c0 26.5-21.5 48-48 48H496c-26.5 0-48-21.5-48-48V391.2l47.6-47.6c21.9-21.9 21.9-57.3 0-79.2l-64-64zM272 240v32h96V240c0-9.7 5.8-18.5 14.8-22.2s19.3-1.7 26.2 5.2l64 64c9.4 9.4 9.4 24.6 0 33.9l-64 64c-6.9 6.9-17.2 8.9-26.2 5.2s-14.8-12.5-14.8-22.2V336H272v32c0 9.7-5.8 18.5-14.8 22.2s-19.3 1.7-26.2-5.2l-64-64c-9.4-9.4-9.4-24.6 0-33.9l64-64c6.9-6.9 17.2-8.9 26.2-5.2s14.8 12.5 14.8 22.2z\"/></svg>`{=html}'\ntitle-slide-attributes:\n  data-background-image: ../images/bg.png\n  # data-background-size: stretch\n  # data-slide-number: none\nformat: \n  live-revealjs: \n    output-file: 16-infer-cat-slides.html\n    # theme: slides.scss\n    code-line-numbers: true\nwebr:\n  cell-options:\n    autorun: false\n  packages:\n    - tidyverse\nknitr:\n  opts_chunk:\n    out-width: 100%\n    echo: false\n---\n\n\n# {visibility=\"hidden\"}\n\n\\def\\bx{\\mathbf{x}}\n\\def\\bg{\\mathbf{g}}\n\\def\\bw{\\mathbf{w}}\n\\def\\bbeta{\\boldsymbol \\beta}\n\\def\\bX{\\mathbf{X}}\n\\def\\by{\\mathbf{y}}\n\\def\\bH{\\mathbf{H}}\n\\def\\bI{\\mathbf{I}}\n\\def\\bS{\\mathbf{S}}\n\\def\\bW{\\mathbf{W}}\n\\def\\T{\\text{T}}\n\\def\\cov{\\mathrm{Cov}}\n\\def\\cor{\\mathrm{Corr}}\n\\def\\var{\\mathrm{Var}}\n\\def\\E{\\mathrm{E}}\n\\def\\bmu{\\boldsymbol \\mu}\n\\DeclareMathOperator*{\\argmin}{arg\\,min}\n\\def\\Trace{\\text{Trace}}\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n<!-- begin: webr fodder -->\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n<!-- end: webr fodder -->\n\n\n<!-- # [Hypothesis Testing]{.orange}{background-image=\"https://upload.wikimedia.org/wikipedia/commons/4/42/William_Sealy_Gosset.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"} -->\n\n# Inference for Categorical Data\n\n- ### Inference for a Single Proportion\n- ### Difference of Two Proportions\n- ### Test for Goodness of Fit\n- ### Test of Independence\n\n\n\n# Categorical Variable, Count and Proportion\n\n## One Categorical Variable with Two Categories\n\n- A categorical variable **Gender** having 2 categories Male and Female.\n\n:::: columns\n\n::: {.column width=\"50%\"}\n\n::: center\n\n<!-- | Subject     | Male | Female | -->\n<!-- |:--------:|:--------:|:--------:| -->\n<!-- | 1 | x |   |   -->\n<!-- | 2 |   | x | -->\n<!-- | $\\vdots$  | $\\vdots$ | $\\vdots$  | -->\n<!-- | $n$ | x |   | -->\n\n| Subject     | Gender |\n|:--------:|:--------:|\n| 1 | Male | \n| 2 | Female  | \n| $\\vdots$  | $\\vdots$ | \n| $n$ | Female | \n\n\n\n:::\n\n<br>\n\n::: center\n\n**One-way frequency/count table**\n\n| $X$     | Count |\n|:--------:|:--------:|\n| Male   | $y$    |  \n| Female | $n-y$ |\n\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/class.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n\n- The sample male proportion is $y/n$. \n\n- Goal: **estimate or test gender ratio or the male population proportion**\n\n:::\n\n::::\n\n\n## Probability Distribution for Count Data: Two Levels\n\n- The number of Male can be viewed as a random variable because the *count $y$ varies from sample to sample*.\n\n::: question\nWhat probability distribution might be appropriate for the count $Y$?\n:::\n\n. . .\n\n- $binomial(n, \\pi)$ could be a good option for the count data with 2 categories.\n\n  + Fixed number of trials. <span style=\"color:blue\"> (Fixed $n$ subjects) </span>\n  \n  + Each trial results in one of two outcomes. <span style=\"color:blue\"> (Either $M$ or $F$) </span>\n  \n  + Trials are independent. <span style=\"color:blue\"> (If sample subjects randomly) </span>\n  \n. . .\n\n- If the proportion of being in category $M$ is $\\pi$, the count $Y$ has $$P(Y = y \\mid n, \\pi) = \\frac{n!}{y!(n-y)!}\\pi^{y}(1-\\pi)^{n-y}$$\n\n- Our job is to do inference about $\\pi$.\n\n<!-- - We'd like to do inference about the president's approval rate (single proportion) or whether male and female's president's approval proportions are different (2 proportions). -->\n\n\n::: notes\n\n- or in general the count $(Y_M, Y_F)$ has the probability function\n$$P(Y_M = y, Y_F = n-y \\mid n, \\pi) = \\frac{n!}{y!(n-y)!}\\pi^{y}(1-\\pi)^{n-y}$$\n- One of our goals in categorical data analysis is to **estimate or test population proportions of categories**, here $M$ and $F$, or $(\\pi, 1-\\pi)$.\n\n:::\n\n\n# [Inference for a Single Proportion]{.orange}{background-image=\"./images/16-infer-cat/karl_pearson.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n\n## Inference About a Single Population Proportion\n\n<!-- - We start with a binomial distribution with $\\pi = P(\\text{success})$. -->\n- **Example: Exit Poll** Suppose we collected data on 1,000 voters in an election with only two candidates: **R** and **D**.\n\n:::: columns\n\n::: {.column width=\"70%\"}\n\n::: center\n\n|Voter | R | D |\n|:-----:|:-----:|:-----:|\n|1  | x |   |\n|2  |   |  x |\n| $\\vdots$  | $\\vdots$ | $\\vdots$  |\n|1000| x |   |\n\n:::\n\n:::\n\n\n::: {.column width=\"30%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/vote.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n<br>\n\n- Based on the data, we want to predict who won the election.\n\n\n## Poll Example Cont'd\n\n:::: columns\n\n::: {.column width=\"50%\"}\n\n- Let $Y$ be the number of voters voted for **R**.\n\n- Assume $Y \\sim binomial(n = 1000, \\pi)$.\n\n- $\\pi = P(\\text{a voter voted for R}) =$ population proportion of all voters voted for R: A **unknown** parameter to be estimated or tested.\n\n- Predict whether or not **R won the election**.\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n::: center\n\n|Voter | R | D |\n|:-----:|:-----:|:-----:|\n|1  | x |   |\n|2  |   |  x |\n| $\\vdots$  | $\\vdots$ | $\\vdots$  |\n|1000| x |   |\n\n| Candidate | Count | Proportion\n|:--------:|:--------:|:--------:|\n| R   | $y$    | $\\hat{\\pi} = y/n$  \n| D   | $n-y$ | $1-\\hat{\\pi} = 1- \\frac{y}{n}$  \n\n:::\n\n:::\n\n::::\n\n::: question\nWhat are $H_0$ and $H_1$?\n:::\n\n. . .\n\n- <span style=\"color:blue\"> $\\begin{align} &H_0: \\pi \\le 1/2 \\\\ &H_1: \\pi > 1/2 \\text{ (more than half voted for R)} \\end{align}$ </span>\n\n<!-- - If we reject $H_0$ in favor of $H_1$ at $\\alpha = 0.05$, this would mean that we predict that **R won the election**, but with $P(\\text{False Discovery}) = 0.05$. -->\n\n\n## Hypothesis Testing for $\\pi$\n\n- Step 0: Assumptions\n  +  <span style=\"color:blue\"> $n\\pi_0 \\ge 5$ and $n(1-\\pi_0) \\ge 5$ (the larger, the better) </span>\n\n- Step 1: Null and Alternative Hypothesis\n  + <span style=\"color:blue\"> $\\begin{align} &H_0: \\pi = \\pi_0 \\\\ &H_1: \\pi > \\pi_0 \\text{ or } \\pi < \\pi_0 \\text{ or } \\pi \\ne \\pi_0 \\end{align}$ </span>\n\n\n- Step 2: Set $\\alpha$\n\n  <!-- + $\\alpha = P(\\text{Reject } H_0 \\mid H_0 \\text{ is true})$ -->\n  \n  \n- Step 3: Test Statistic\n  +  <span style=\"color:blue\"> Under $H_0$, $z_{test} = \\dfrac{\\hat{\\pi} - \\pi_0}{\\sqrt{\\frac{\\pi_0(1-\\pi_0)}{n}}}$  where $\\hat{\\pi} = \\frac{y}{n} =$ sample proportion </span>\n\n. . .\n\n::: alert\nThe sampling distribution of $\\hat{\\pi}$ is approximately normal with mean $\\pi$ and standard error $\\sqrt{\\frac{\\pi(1-\\pi)}{n}}$ if $y_i$ are independent and the assumptions are satisfied.\n:::\n\n::: notes\n<!-- .question[ -->\n<!-- Why the test statistic is a $z$ (standard normal) statistic? -->\n<!-- ] -->\n:::\n\n\n## Hypothesis Testing for $\\pi$\n\n\n- Step 4-c: Critical Value $z_{\\alpha}$ (one-tailed) or $z_{\\alpha/2}$ (two-tailed)\n\n- Step 5-c: Draw a Conclusion Using Critical Value Method\n  <!-- + <span style=\"color:blue\">  Reject $H_0$ in favor of $H_1$ if </span> -->\n    - <span style=\"color:blue\"> $H_1: \\pi > \\pi_0$: Reject $H_0$ in favor of $H_1$ if $z > z_{\\alpha}$ </span>\n    - <span style=\"color:blue\"> $H_1: \\pi < \\pi_0$: Reject $H_0$ in favor of $H_1$ if $z < -z_{\\alpha}$ </span>\n    - <span style=\"color:blue\"> $H_1: \\pi \\ne \\pi_0$: Reject $H_0$ in favor of $H_1$ if $|z| > z_{\\alpha/2}$ </span>\n\n- Step 6: Restate the Conclusion in Nontechnical Terms, and Address the Original Claim\n\n\n## Poll Example Cont'd (Hypothesis Testing)\n\n- In an exit poll of 1,000 voters, 520 voted for **R**, one of the two candidates.\n\n- Step 0:<span style=\"color:blue\"> $n\\pi_0 = 1000(1/2) = 500 \\ge 5$ and $n(1-\\pi_0) \\ge 5$ </span>\n\n- Step 1: <span style=\"color:blue\"> $\\begin{align} &H_0: \\pi \\le 1/2 \\\\ &H_1: \\pi > 1/2 \\end{align}$ </span>\n\n- Step 2: <span style=\"color:blue\"> $\\alpha = 0.05$ </span>\n\n- Step 3: <span style=\"color:blue\"> $z_{test} = \\frac{\\hat{\\pi} - \\pi_0}{\\sqrt{\\frac{\\pi_0(1-\\pi_0)}{n}}} =  \\frac{\\frac{520}{1000} - 0.5}{\\sqrt{\\frac{0.5(1-0.5)}{1000}}} = 1.26$ </span>\n\n. . .\n\n- Step 4: <span style=\"color:blue\"> $z_{\\alpha} = z_{0.05} = 1.645$ </span>\n\n- Step 5: <span style=\"color:blue\">  Reject $H_0$ in favor of $H_1$ if $z_{test} > z_{\\alpha}$. Since $z_{test} < z_{\\alpha}$, we do not reject $H_0$.  </span>\n\n- Step 6: <span style=\"color:blue\">  We do not have sufficient evidence to conclude that R won.  </span>\n\n- We make the same conclusion based on $p$-value. \n\n$$ p\\text{-value} = P(Z > 1.26) = 0.1 > 0.05$$\n\n::: notes\nIs there a sufficient evidence to conclude at $\\alpha = 0.05$ that R won the election?\n:::\n\n\n## Confidence Interval for $\\pi$\n\n- Assumptions:  $n\\hat{\\pi} \\ge 5$ and $n(1-\\hat{\\pi}) \\ge 5$\n\n- A $100(1 - \\alpha)\\%$ confidence interval for $\\pi$ is\n$$\\hat{\\pi} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\pi(1-\\pi)}{n}}$$ where $\\hat{\\pi} = y/n$.\n\n. . .\n\n- $\\pi$ is unknown and use the estimate $\\hat{\\pi}$ instead: $$\\hat{\\pi} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{\\pi}(1-\\hat{\\pi})}{n}}$$\n\n\n::: alert\n👉 No hypothesized value $\\pi_0$ in the confidence interval.\n:::\n\n\n## Poll Example Cont'd  (Confidence Interval)\n\n- Assumption: $n\\hat{\\pi} = 1000(0.52) = 520 \\ge 5$ and $n(1-\\hat{\\pi}) = 480 \\ge 5$.\n\n- Estimate the proportion of all voters voted for **R** using 95% confidence interval:\n\n$$\\hat{\\pi} \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{\\pi}(1-\\hat{\\pi})}{n}} = 0.52 \\pm z_{0.025}\\sqrt{\\frac{0.52(1-0.52)}{1000}} = (0.49, 0.55).$$\n\n. . .\n\n::: midi\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n# Use alternative = \"two.sided\" to get CI\nprop.test(x = 520, n = 1000, p = 0.5, alternative = \"greater\", correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  520 out of 1000, null probability 0.5\nX-squared = 2, df = 1, p-value = 0.1\nalternative hypothesis: true p is greater than 0.5\n95 percent confidence interval:\n 0.494 1.000\nsample estimates:\n   p \n0.52 \n```\n\n\n:::\n:::\n\n\n:::\n\n\n# [Difference of Two Proportions]{.orange}{background-image=\"./images/16-infer-cat/karl_pearson.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n\n## Inference About Two Population Proportions\n\n:::: columns\n\n::: {.column width=\"50%\"}\n<br>\n\n::: midi\n| | Group 1  (M) | Group 2 (F)\n|:-----:|:-----:|:-----:\n| trials | $n_1$ | $n_2$\n| number of successes | $Y_1$ | $Y_2$ \n| distribution | $binomial(n_1, \\pi_1)$ | $binomial(n_2, \\pi_2)$ \n\n- $\\pi_1$: Population proportion of success of Group 1\n- $\\pi_2$: Population proportion of success of Group 2\n:::\n\n::: center\n\n|Voter | Gender | Approve |\n|:-----:|:-----:|:-----:|\n|1  | M | Yes  |\n|2  | F  |  Yes |\n| $\\vdots$  | $\\vdots$ | $\\vdots$  |\n|1000| F | No  |\n\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n- Is male's president approval rate $\\pi_1$ higher than the female's approval rate $\\pi_2$?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/trump_rate.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n::: notes\n- Comparing two population proportions $\\pi_1$ and $\\pi_2$.\n:::\n\n\n\n## Hypothesis Testing for $\\pi_1$ and $\\pi_2$\n\n- Step 0: Assumptions\n  +  <span style=\"color:blue\"> $n_1\\hat{\\pi}_1 \\ge 5$, $n_1(1-\\hat{\\pi}_1) \\ge 5$ and $n_2\\hat{\\pi}_2 \\ge 5$, $n_2(1-\\hat{\\pi}_2) \\ge 5$ </span>\n  \n- Step 1: Null and Alternative Hypothesis\n  + <span style=\"color:blue\"> $\\begin{align}  &H_0: \\pi_1 = \\pi_2 \\\\ &H_1: \\pi_1 > \\pi_2 \\text{ or } \\pi_1 < \\pi_2 \\text{ or } \\pi_1 \\ne \\pi_2 \\end{align}$ </span>\n\n- Step 2: Set $\\alpha$\n\n- Step 3: Test Statistic\n  +  <span style=\"color:blue\"> $z_{test} = \\dfrac{\\hat{\\pi}_1 - \\hat{\\pi}_2}{\\sqrt{\\bar{\\pi}(1-\\bar{\\pi})(\\frac{1}{n_1} + \\frac{1}{n_2}})}$, $\\bar{\\pi} = \\frac{y_1+y_2}{n_1+n_2}$ is the **pooled** sample proportion estimating $\\pi$ </span>\n  \n\n::: notes\n\n$z_{test} = \\dfrac{\\hat{\\pi}_1 - \\hat{\\pi}_2}{\\sqrt{\\frac{\\bar{\\pi}(1-\\bar{\\pi})}{n_1} + \\frac{\\bar{\\pi}(1-\\bar{\\pi})}{n_2}}} = \\dfrac{\\hat{\\pi}_1 - \\hat{\\pi}_2}{\\sqrt{\\bar{\\pi}(1-\\bar{\\pi})(\\frac{1}{n_1} + \\frac{1}{n_2}})}$, $\\bar{\\pi} = \\frac{y_1+y_2}{n_1+n_2}$ is the pooled sample proportion that is an estimate of $\\pi$\n\n:::\n\n\n## Hypothesis Testing for $\\pi_1$ and $\\pi_2$\n\n- Step 4-c: Find the Critical Value $z_{\\alpha}$ (one-tailed) or $z_{\\alpha/2}$ (two-tailed)\n\n- Step 5-c: Draw a Conclusion Using Critical Value Method\n  + <span style=\"color:blue\">  Reject $H_0$ in favor of $H_1$ if </span>\n    - <span style=\"color:blue\"> $H_1: \\pi_1 > \\pi_2$: Reject $H_0$ in favor of $H_1$ if $z > z_{\\alpha}$ </span>\n    - <span style=\"color:blue\"> $H_1: \\pi_1 < \\pi_2$: Reject $H_0$ in favor of $H_1$ if $z < -z_{\\alpha}$ </span>\n    - <span style=\"color:blue\"> $H_1: \\pi_1 \\ne \\pi_2$: Reject $H_0$ in favor of $H_1$ if $|z| > z_{\\alpha/2}$ </span>\n    \n- Step 6: Restate the Conclusion in Nontechnical Terms, and Address the Original Claim\n\n\n\n## Example: Effectiveness of Learning\n\n:::: columns\n\n::: {.column width=\"70%\"}\n\nA study on 300 students to compare the effectiveness of learning Statistics via online and in-person classes.\n\n- Randomly assign\n  + 125 students to the online program\n  + the remaining 175 to the in-person program.\n\n:::\n\n\n::: {.column width=\"30%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/online_learning.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n|Exam Results | Online Instruction | In-Person Instruction |\n|:-----:|:-----:|:-----:|\n|Pass  | 94   | 113 |\n|Fail  | 31   | 62  |\n|Total | 125  | 175 |\n\n- Is there sufficient evidence to conclude that the online program is more effective than the traditional in-person program at $\\alpha=0.05$?\n\n\n\n## Example: Effectiveness of Learning Cont'd (Testing)\n\n- Step 1: <span style=\"color:blue\"> $H_0: \\pi_1 = \\pi_2$ vs. $H_1: \\pi_1 > \\pi_2$ </span>  \n$\\pi_1$ $(\\pi_2)$ is the population proportion of students passing the exam under the online (in-person) program.\n\n. . .\n\n- Step 0:<span style=\"color:blue\"> $\\hat{\\pi}_1 = 94/125 = 0.75$ and $\\hat{\\pi}_2 = 113/175 = 0.65$.  \n$n_1\\hat{\\pi}_1 = 94 > 5$, $n_1(1-\\hat{\\pi}_1) = 31 > 5$, and $n_2\\hat{\\pi}_2 = 113 > 5$, $n_2(1-\\hat{\\pi}_2) = 62 > 5$ </span>\n\n. . .\n\n- Step 2: <span style=\"color:blue\"> $\\alpha = 0.05$ </span>\n\n. . .\n\n- Step 3: <span style=\"color:blue\"> $\\bar{\\pi} = \\frac{94+113}{125+175} = 0.69$. $z_{test} = \\dfrac{\\hat{\\pi}_1 - \\hat{\\pi}_2}{\\sqrt{\\bar{\\pi}(1-\\bar{\\pi})(\\frac{1}{n_1} + \\frac{1}{n_2}})} = \\frac{0.75 - 0.65}{\\sqrt{0.69(1-0.69)(\\frac{1}{125} + \\frac{1}{175})}} = 1.96$ </span>\n\n. . .\n\n- Step 4: <span style=\"color:blue\"> $z_{\\alpha} = z_{0.05} = 1.645$ </span>\n\n. . .\n\n- Step 5: <span style=\"color:blue\">  Reject $H_0$ in favor of $H_1$ if $z_{test} > z_{\\alpha}$. Since $z_{test} > z_{\\alpha}$, we reject $H_0$.  </span>\n\n. . .\n\n- Step 6: <span style=\"color:blue\">  We have sufficient evidence to conclude that the online program is more effective. </span>\n\n## Confidence Interval for $\\pi_1 - \\pi_2$ \n\n- A $100(1 - \\alpha)\\%$ confidence interval for $\\pi_1 - \\pi_2$ is \n\n$$\\hat{\\pi}_1 - \\hat{\\pi}_2 \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{\\pi}_1(1-\\hat{\\pi}_1)}{n_1}+\\frac{\\hat{\\pi}_2(1-\\hat{\\pi}_2)}{n_2}}$$\n\n- Requirements: $n_1\\hat{\\pi}_1 \\ge 5$, $n_1(1-\\hat{\\pi}_1) \\ge 5$ and $n_2\\hat{\\pi}_2 \\ge 5$, $n_2(1-\\hat{\\pi}_2) \\ge 5$\n\n\n## Example: Effectiveness of Learning Cont'd (CI)\n\n- Want to know how much effective is the online program. \n\n- Estimate $\\pi_1 - \\pi_2$ using a $95\\%$ confidence interval:\n\n$$\\hat{\\pi}_1 - \\hat{\\pi}_2 \\pm z_{\\alpha/2}\\sqrt{\\frac{\\hat{\\pi}_1(1-\\hat{\\pi}_1)}{n_1}+\\frac{\\hat{\\pi}_2(1-\\hat{\\pi}_2)}{n_2}}$$\n\n- $z_{0.05/2} = 1.96$\n\n- The 95% confidence interval is\n\n$$0.75 - 0.65 \\pm 1.96\\sqrt{\\frac{(0.75)(1-0.75)}{125} + \\frac{(0.65)(1-0.65)}{175}}\\\\\n = (0.002, 0.210)$$\n\n\n## Implementation in R\n\n::: midi\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n# Use alternative = \"two.sided\" to get CI\nprop.test(x = c(94, 113), n = c(125, 175), alternative = \"greater\", correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` my_class500\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  c(94, 113) out of c(125, 175)\nX-squared = 4, df = 1, p-value = 0.02\nalternative hypothesis: greater\n95 percent confidence interval:\n 0.0193 1.0000\nsample estimates:\nprop 1 prop 2 \n 0.752  0.646 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nprop_ci <- prop.test(x = c(94, 113), n = c(125, 175), alternative = \"two.sided\", correct = FALSE)\nprop_ci$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00259 0.20998\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n# [Test for Goodness of Fit]{.orange}{background-image=\"./images/16-infer-cat/karl_pearson.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n\n\n## Categorical Variable with More Than 2 Categories\n\n:::: columns\n\n::: {.column width=\"50%\"}\n\n- A categorical variable has $k$ categories $A_1, \\dots, A_k$.\n\n::: center\n\n<!-- | Subject     | $A_1$ | $A_2$ | $\\cdots$ | $\\cdots$ | $A_k$|   -->\n<!-- |:--------:|:--------:|:--------:|:--------:|:--------:|:--------:| -->\n<!-- | 1 | x |   |  |  |   | -->\n<!-- | 2 |   | x |  |  |   |  -->\n<!-- | 3 |   |  |   |  |  x | -->\n<!-- | $\\vdots$  |  |   |  |  |   | -->\n<!-- | $n$ |   |   |  | x |  | -->\n\n\n| Subject  | Variable|  \n|:--------:|:--------:|\n| 1 | $A_2$ |\n| 2 | $A_4$  |\n| 3 |  $A_1$ |\n| 4 |  $A_3$ |\n| 5 |  $A_k$ |\n| $\\vdots$  | $\\vdots$ |\n| $n$ | $A_3$ |\n\n\n\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n- With the size $n$, for categories $A_1, \\dots , A_k$, their observed count is $O_1, \\dots, O_k$, and $\\sum_{i=1}^kO_i = n$.\n\n- One-way count table:\n\n::: center\n\n| $A_1$  | $A_2$ | $\\cdots$ | $A_k$ | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|\n| $O_1$ | $O_2$   |  $\\cdots$ |  $O_k$  | $n$ | \n\n:::\n\n\n:::\n\n::::\n\n\n## Example: More Than 2 Categories\n\n:::: columns\n\n::: {.column width=\"50%\"}\n\n*Are the selected jurors are racially representative of the population?*\n\n- **Idea**: If the jury is representative of the population, the proportions in the sample should reflect the population of eligible jurors, i.e., registered\nvoters.\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/diversity.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Representation in juries | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Registered voters | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$   |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ | \n\n\n## Example: More Than 2 Categories\n\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Representation in juries | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Registered voters | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$   |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ |\n\n\n::: {.fragment}\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Representation in juries | $O_1/n = 0.75$ | $O_2/n = 0.09$   |  $O_3/n = 0.09$ |  $O_4/n = 0.07$  | $1.00$ | \n| Registered voters | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$   |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ |\n\n:::\n\n\n<!-- ::: {.fragment} -->\n\n<!-- |  | White  | Black | Hispanic | Asian | Total | -->\n<!-- |:-----:|:-----:|:-----:|:-----:|:-----:| -->\n<!-- | Representation in juries | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ |  -->\n<!-- | Hypothesized expected number | $275*\\pi_1 = 198$ | $275*\\pi_2 = 19.25$  | $275*\\pi_3 = 33$ | $275*\\pi_4 = 24.75$ | $n=275$ |  -->\n\n<!-- ::: -->\n<!-- **198** | **19.25**   |  **33** | **24.75** | 275 | -->\n\n<!-- | Population Proportion | **0.72** | **0.07** |  **0.12** |  **0.09**  | 1.00 |  -->\n\n<!-- |  | White  | Black | Hispanic | Asian | Total | -->\n<!-- |:-----:|:-----:|:-----:|:-----:|:-----:| -->\n<!-- | Representation in juries | 0.75 | 0.09   |  0.09 | 0.07  | 1.00 |  -->\n<!-- | Registered voters | 0.72 | 0.07   |  0.12 |  0.09  | 1.00 |  -->\n\n\n\n\n::: notes\n\nWhile the proportions in the juries do not precisely represent the population proportions, it is unclear whether these data provide convincing evidence that the sample is not representative. If the jurors really were randomly sampled from the registered voters, we might expect small differences due to chance. However, unusually large differences may provide convincing evidence that the juries were not representative.\n\n:::\n\n## Example: More Than 2 Categories\n\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Representation in juries | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Registered voters | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$   |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ |\n\n\n::: question\n\nIf the individuals are randomly selected to serve on a jury, about how many of the 275 people would we expect to be white? How about Hispanic?\n\n:::\n\n\n. . .\n\n- About $72\\%$ of the population is white, so we would expect about $72\\%$ of the jurors to be white: $0.72 \\times 275 = 198$.\n\n<!-- - We expect about $12\\%$ of the jurors to be Hispanic, which corresponds to about $0.12 \\times 275 = 33$ Hispanic jurors. -->\n\n\n::: {.fragment}\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:--------:|:-----:|:-----:|:-----:|:-----:|\n| Representation in juries | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Hypothesized expected number | $275 \\times \\pi_1^0 = 198$ | $275 \\times \\pi_2^0 = 19.25$  | $275 \\times \\pi_3^0 = 33$ | $275 \\times \\pi_4^0 = 24.75$ | $n=275$ | \n\n:::\n<!-- **198** | **19.25**   |  **33** | **24.75** | 275 | -->\n\n<!-- | Population Proportion | **0.72** | **0.07** |  **0.12** |  **0.09**  | 1.00 |  -->\n\n<!-- |  | White  | Black | Hispanic | Asian | Total | -->\n<!-- |:-----:|:-----:|:-----:|:-----:|:-----:| -->\n<!-- | Representation in juries | 0.75 | 0.09   |  0.09 | 0.07  | 1.00 |  -->\n<!-- | Registered voters | 0.72 | 0.07   |  0.12 |  0.09  | 1.00 |  -->\n\n\n\n## Goodness-of-Fit Test\n\n::: question\nAre the proportions (counts) of juries *close enough* to the proportions (counts) of registered voters, so that we are confident saying that the jurors really were *randomly sampled* from the registered voters?\n:::\n\n- A **goodness-of-fit test** tests the hypothesis that the observed frequency distribution fits or conforms to some claim distribution.\n\n<!-- ::: question -->\n\n<!-- In the jury example, what is our observed frequency distribution, and what is our claim distribution? -->\n\n<!-- ::: -->\n\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Observed Count | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Expected Count | $E_1 = 198$ | $E_2 = 19.25$   |  $E_3 = 33$ |  $E_4 = 24.75$  | $n = 275$ |\n| Proportion under $H_0$ | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$ |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ | \n\n::: notes\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|\n| **Observed** Count | 205 | 26   |  25 |  19  | 275 | \n| **Expected** Count | **198** | **19.25**   |  **33** | **24.75** | 275 | \n| Population Proportion | **0.72** | **0.07** |  **0.12** |  **0.09**  | 1.00 | \n\n  + Given a sample of cases that can be classified into several (more than 2) groups, determine if the sample is representative of the general population.\n  + Evaluate whether data resemble a particular distribution.\n- The sample proportion represented from each race among the 275 jurors was not a precise match for any ethnic group. While some sampling variation is expected, we would expect the sample proportions to be fairly similar to the population proportions if there is no bias on juries.\n- We need to test whether the differences are strong enough to provide convincing evidence that the jurors are not a random sample.\n\n:::\n\n\n## Goodness-of-Fit Test\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-------------:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| **Observed** Count | 205 | 26   |  25 |  19  | 275 | \n| **Expected** Count | **198** | **19.25**   |  **33** | **24.75** | 275 | \n| Population Proportion $(H_0)$ | **0.72** | **0.07** |  **0.12** |  **0.09**  | 1.00 |  \n\n<!-- - The sample proportions are similar to the population ones if no bias on juries. -->\n- **Observed** Count and **Expected** Count are similar if no bias on juries.\n\n- Test whether the differences are strong enough to provide convincing evidence that the jurors are not a random sample of registered voters.\n\n<span style=\"color:blue\"> $\\begin{align} &H_0: \\text{No racial bias in who serves on a jury, and } \\\\ &H_1: \\text{There is racial bias in juror selection} \\end{align}$ </span>\n  \n. . .\n\n<span style=\"color:blue\"> $\\begin{align} &H_0: \\pi_1 = \\pi_1^0,  \\pi_2 = \\pi_2^0, \\dots, \\pi_k = \\pi_k^0\\\\ &H_1: \\pi_i \\ne \\pi_i^0 \\text{ for some } i \\end{align}$ </span>\n\n\n::: notes\n\n- While some sampling variation is expected, we would expect the sample proportions to be similar to the population proportions if there is no bias on juries.\n\n- We need to test whether the differences are strong enough to provide convincing evidence that the jurors are not a random sample of registered voters.\n\n- $\\quad\\text{the observed counts reflect natural sampling fluctuation.}$\n\n:::\n\n\n## Goodness-of-Fit Test Statistic\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Observed Count | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Expected Count | $E_1 = 198$ | $E_2 = 19.25$   |  $E_3 = 33$ |  $E_4 = 24.75$  | $n = 275$ |\n| Proportion under $H_0$ | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$ |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ | \n\n\n- <span style=\"color:blue\">  Under $H_0$, $\\chi^2_{test} = \\frac{(O_1 - E_1)^2}{E_1} + \\frac{(O_2 - E_2)^2}{E_2} + \\cdots + \\frac{(O_k - E_k)^2}{E_k}$, $E_i = n\\pi_i^0, i = 1, \\dots, k$ </span>\n\n- Reject $H_0$ if <span style=\"color:blue\"> $\\chi^2_{test} > \\chi^2_{\\alpha, df}$, $df = k-1$ </span>\n\n- Require each $E_i \\ge 5$, $i = 1, \\dots, k$.\n\n\n::: notes\n\n- $\\chi^2_{test}$ summarizes how strongly the observed counts tend to deviate from the expected counts or null counts.\n- 4720: In the textbook, $E_i \\ge 1$ and no more than $20\\%$ of the $E_i$s are less than 5. \n\n:::\n\n## Goodness-of-Fit Test Example\n\n|  | White  | Black | Hispanic | Asian | Total |\n|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|\n| Observed Count | $O_1 = 205$ | $O_2 = 26$   |  $O_3 = 25$ |  $O_4 = 19$  | $n = 275$ | \n| Expected Count | $E_1 = 198$ | $E_2 = 19.25$   |  $E_3 = 33$ |  $E_4 = 24.75$  | $n = 275$ |\n| Proportion under $H_0$ | $\\pi_1^0 = 0.72$ | $\\pi_2^0 = 0.07$ |  $\\pi_3^0 = 0.12$ |  $\\pi_4^0 = 0.09$  | $1.00$ | \n\n- Under $H_0$, $\\chi^2_{test} = \\frac{(205 - 198)^2}{198} + \\frac{(26 - 19.25)^2}{19.25} + \\frac{(25 - 33)^2}{33} + \\frac{(19 - 24.75)^2}{24.75} = 5.89$\n\n- $\\chi^2_{0.05, 3} = 7.81$.\n\n- Do not reject $H_0$ in favor of $H_1$. \n\n- The data do not provide convincing evidence of racial bias in the juror selection.\n\n\n\n## Goodness-of-Fit Test in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nobs <- c(205, 26, 25, 19)\npi_0 <- c(0.72, 0.07, 0.12, 0.09)\n\n## Use chisq.test() function\nchisq.test(x = obs, p = pi_0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  obs\nX-squared = 6, df = 3, p-value = 0.1\n```\n\n\n:::\n:::\n\n\n\n::: notes\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 198.0  19.3  33.0  24.8\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX-squared \n     5.89 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.117\n```\n\n\n:::\n:::\n\n\n:::\n\n\n# [Test of Independence]{.orange}{background-image=\"./images/16-infer-cat/karl_pearson.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n## Test of Independence (Contingency Table)\n\n- Have TWO categorical variables, and want to test **whether or not the two variables are independent**.\n\n. . .\n\n\n:::: columns\n\n<span style=\"color:blue\"> Does the \"Opinion on President's Job Performance\" depends on \"Gender\"?  </span>\n\n\n::: {.column width=\"55%\"}\n\n- **Job performance**: approve, disapprove, no opinion\n\n- **Gender**: male, female\n\n::: midi\n|Voter | Gender | Performance |\n|:-----:|:-----:|:-----:|\n|1  | M | approve  |\n|2  | F  |  disapprove |\n| $\\vdots$  | $\\vdots$ | $\\vdots$  |\n|n| F | disapprove  |\n:::\n\n|  | Approve  | Disapprove | No Opinion \n|:-----:|:-----:|:-----:|:-----:|\n| **Male** | 18 | 22  |  10 |\n| **Female** | 23 | 20 | 12 |\n\n:::\n\n\n\n::: {.column width=\"45%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/approval_rate.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n\n::::\n\n\n\n::: notes\n\nWhen we consider a two-way table, we often would like to know, are these variables related in any way? That is, are they dependent (versus independent)?\n\n:::\n\n\n## Test of Independence: Expected Count\n\n- Compute the *expected* count of each cell in the two-way table under the condition that the *two variables __were independent__* with each other.\n\n\n|  | Approve  | Disapprove | No Opinion | Total | \n|:-----:|:-----:|:-----:|:-----:|:-----:|\n| **Male** | 18 (19.52) | 22 (20)  |  10 (10.48) | 50 |\n| **Female** | 23 (21.48) | 20 (22) | 12  (11.52)| 55 |\n| **Total** | 41 | 42 | 22 | 105 |\n\n\n. . .\n\n- The expected count for the $i$th row and $j$th column:\n\n$$\\text{Expected Count}_{\\text{row i; col j}} = \\frac{\\text{(row i total}) \\times (\\text{col j total})}{\\text{table total}}$$\n\n\n::: notes\n\n- As test of goodness-of-fit, we want to compute the expected count of each cell in the two-way table under the condition that the two variables were independent with each other.\n\n:::\n\n\n## Test of Independence Procedure\n\n- Require every $E_{ij} \\ge 5$ in the contingency table. \n\n- <span style=\"color:blue\"> $\\begin{align} &H_0: \\text{Two variables are independent }\\\\ &H_1: \\text{The two are dependent (associated) } \\end{align}$</span>\n\n- $\\chi^2_{test} = \\sum_{i=1}^r\\sum_{j=1}^c\\frac{(O_{ij} - E_{ij})^2}{E_{ij}}$, where $r$ is the number of rows and $c$ is the number of columns in the table.\n\n- Reject $H_0$ if $\\chi^2_{test} > \\chi^2_{\\alpha, \\, df}$, $df = (r-1)(c-1)$.\n\n\n::: notes\n\nIn the 4720 textbook, every $E_{ij} \\ge 1$ and no more than $20\\%$ of the $E_{ij}$s less than 5. \n\n:::\n\n\n## Test of Independence Example\n\n|  | Approve  | Disapprove | No Opinion | Total | \n|:-----:|:-----:|:-----:|:-----:|:-----:|\n| **Male** | 18 (19.52) | 22 (20)  |  10 (10.48) | 50 |\n| **Female** | 23 (21.48) | 20 (22) | 12  (11.52)| 55 |\n| **Total** | 41 | 42 | 22 | 105 |\n\n\n- <span style=\"color:blue\"> $\\begin{align} &H_0: \\text{ Opinion does not depend on gender } \\\\ &H_1: \\text{ Opinion and gender are dependent } \\end{align}$</span>\n\n- $\\small \\chi^2_{test} = \\frac{(18 - 19.52)^2}{19.52} + \\frac{(22 - 20)^2}{20} + \\frac{(10 - 10.48)^2}{10.48} + \\frac{(23 - 21.48)^2}{21.48} + \\frac{(20 - 22)^2}{22} + \\frac{(12 - 11.52)^2}{11.52}= 0.65$\n\n- $\\chi^2_{\\alpha, df} =\\chi^2_{0.05, (2-1)(3-1)} = 5.991$.\n\n- Since $\\chi_{test}^2 < \\chi^2_{\\alpha, df}$, we do not reject $H_0$. \n\n- We do not conclude that the Opinion on President's Job Performance depends on Gender.\n\n## Test of Independence in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n(contingency_table <- matrix(c(18, 23, 22, 20, 10, 12), nrow = 2, ncol = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2] [,3]\n[1,]   18   22   10\n[2,]   23   20   12\n```\n\n\n:::\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n## Using chisq.test() function\n(indept_test <- chisq.test(contingency_table))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  contingency_table\nX-squared = 0.7, df = 2, p-value = 0.7\n```\n\n\n:::\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nqchisq(0.05, df = (2 - 1) * (3 - 1), lower.tail = FALSE)  ## critical value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.99\n```\n\n\n:::\n:::\n\n\n\n\n## AI Education Research\n\n- Help Marquette to offer AI-related courses, and better teaching using AI!\n\n- <https://carrollu.qualtrics.com/jfe/form/SV_07bFl5NeSI8tIWO>\n\n\n:::: columns\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/survey.png){fig-align='center' width=70%}\n:::\n:::\n\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/16-infer-cat/qrcode_survey.png){fig-align='center' width=70%}\n:::\n:::\n\n\n:::\n\n\n::::\n",
    "supporting": [
      "16-infer-cat_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}