{
  "hash": "57904695493b278b2b8769bcada2c77f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Probability Distributions `<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 448 512\" style=\"height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;\"><path d=\"M160 80c0-26.5 21.5-48 48-48h32c26.5 0 48 21.5 48 48V432c0 26.5-21.5 48-48 48H208c-26.5 0-48-21.5-48-48V80zM0 272c0-26.5 21.5-48 48-48H80c26.5 0 48 21.5 48 48V432c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V272zM368 96h32c26.5 0 48 21.5 48 48V432c0 26.5-21.5 48-48 48H368c-26.5 0-48-21.5-48-48V144c0-26.5 21.5-48 48-48z\"/></svg>`{=html}'\ntitle-slide-attributes:\n  data-background-image: ./images/bg.png\n  # data-background-size: stretch\n  # data-slide-number: none\nformat: \n  live-revealjs: \n    output-file: 07-distribution-slides.html\n    # theme: slides.scss\nwebr:\n  cell-options:\n    autorun: false\n  packages:\n    - tidyverse\nknitr:\n  opts_chunk:\n    out-width: 100%\n    echo: false\n---\n\n\n# {visibility=\"hidden\"}\n\n\\def\\bx{\\mathbf{x}}\n\\def\\bg{\\mathbf{g}}\n\\def\\bw{\\mathbf{w}}\n\\def\\bbeta{\\boldsymbol \\beta}\n\\def\\bX{\\mathbf{X}}\n\\def\\by{\\mathbf{y}}\n\\def\\bH{\\mathbf{H}}\n\\def\\bI{\\mathbf{I}}\n\\def\\bS{\\mathbf{S}}\n\\def\\bW{\\mathbf{W}}\n\\def\\T{\\text{T}}\n\\def\\cov{\\mathrm{Cov}}\n\\def\\cor{\\mathrm{Corr}}\n\\def\\var{\\mathrm{Var}}\n\\def\\E{\\mathrm{E}}\n\\def\\bmu{\\boldsymbol \\mu}\n\\DeclareMathOperator*{\\argmin}{arg\\,min}\n\\def\\Trace{\\text{Trace}}\n\n\n\n\n<!-- begin: webr fodder -->\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n<!-- end: webr fodder -->\n\n# [Random Variables]{.orange}{background-image=\"https://upload.wikimedia.org/wikipedia/commons/1/1c/6sided_dice_%28cropped%29.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n## Random Variables\n\n- Recap: A **variable** in a data set is a characteristic that varies from one to another.\n  + A variable can be either categorical or numerical.\n  + Numerical variables can be either **discrete** or **continuous**.\n  \n. . .\n\n- A **random variable**, usually written as $X$ [^1], is a variable whose possible values are **numerical** outcomes determined by **chance** or **randomness** of a procedure or experiment.\n  + <span style=\"color:blue\"> Toss a coin 2 times. $X$ = # of heads. </span> \n  + <span style=\"color:blue\"> $X$ = # of accidents in W. Wisconsin Ave. per day.</span>\n\n  <!-- + $X$ = time (in minutes) until next accident in W. Wisconsin Ave. -->\n\n- A random variable has a **probability distribution** associated with it, accounting for its randomness. \n\n[^1]: Usually in statistics, a capital $X$ represents a random variable and a small $x$ represents a realized value of $X$.\n\n\n\n::: notes\n- Similar to relative frequency table (distribution)\n- A probability distribution is the mathematical function that gives the probabilities of occurrence of different possible outcomes for an experiment in terms of values of r.v. X.\nYes. The possible values of $X$ are numerical $X = 0, 1, 2$ that are determined by randomness of the tossing-coin experiment.\n:::\n\n\n## Discrete and Continuous Random Variables\n\n- A **discrete** random variable takes on a **finite** or **countable** number of values.\n\n- A **continuous** random variable has **infinitely** many values, and the collection of values is **uncountable**.\n\n. . .\n\n- <span style=\"color:blue\"> The number of relationships you've ever had is **discrete** variable because we can count the number and it is finite.</span>\n  + If we can further determine the probability that the number is 0, 1, 2, or any possible number, it is a **discrete random variable**.\n  \n- <span style=\"color:blue\"> Height is **continuous** because it can be any number within a range. </span> \n  + If we have a way to quantify the probability that the height is from any value $a$ to any value $b$, it is a **continuous random variable**.\n\n\n# Probability Distributions\n\n- ### Discrete Distributions\n- ### Continuous Distributions\n\n\n## A Statistician Should Know\n\n::: tiny\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n[![](./images/07-distribution/common_dist.png){fig-align='center' width=45%}](https://github.com/rasmusab/distribution_diagrams)\n:::\n:::\n\n:::\n\n::: notes\n- There are lots of well-known probability distributions out there.\n- The distributions shown here are just a small part of probability distributions\n- In fact there are infinitely many probability distributions.\n- A function that satisfies probability distribution conditions is a probability distribution.\n- You can construct our own probability distribution.\n:::\n\n\n\n# What We Learn Here\n\n- ### Binomial Distribution\n- ### Poisson Distribution\n- ### Normal Distribution\n\n# [Discrete Probability Distributions]{.orange}{background-image=\"./images/07-distribution/Poisson.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n\n## Discrete Probability Distribution\n\n- The **probability (mass) function (pf, pmf)** of a discrete random variable (r.v.) $X$ is a function $P(X = x)$ (or $p(x)$) that assigns a probability for **every** possible number $x$.\n\n- The **probability distribution** for a discrete r.v. $X$ *displays* its **probability function**.\n\n- The display can be a *table*, *graph*, or *mathematical formula* of $P(X = x)$. \n\n. . .\n\n<span style=\"color:blue\"> **Example:** 🪙🪙 Toss a fair coin twice *independently* and $X$ is the number of heads. </span>\n\n- The probability distribution of $X$ as a table is \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|         |     |    |     |\n|:--------|:----|:---|:----|\n|x        |0    |1   |2    |\n|P(X = x) |0.25 |0.5 |0.25 |\n\n\n:::\n:::\n\n\n. . .\n\n::: alert\n👉 $\\{X = x\\}$ is an event corresponding to an event of some experiment.\n:::\n\n. . .\n\n::: question\nWhat is the event that $\\{X = 0\\}$ corresponds to?\n:::\n\n. . .\n\n::: question\nHow do we get $P(X = 0)$, $P(X=1)$ and $P(X=2)$ ?\n:::\n\n## Discrete Probability Distribution as a Graph\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- $0 \\le P(X = x) \\le 1$ for every value $x$ of $X$.\n  + <span style=\"color:blue\"> $x = 0, 1, 2$ </span>\n  \n. . .\n\n- $\\sum_{x}P(X=x) = 1$, where $x$ assumes all possible values.\n  + <span style=\"color:blue\"> $P(X=0) + P(X = 1) + P(X = 2) = 1$ </span>\n  \n. . .\n\n- The probabilities for a discrete r.v. are **additive** because $\\{X = a\\}$ and $\\{X = b\\}$ are *disjoint* for any possible values $a \\ne b$.\n  + <span style=\"color:blue\"> $P(X = 1 \\text{ or } 2) = P(\\{X = 1\\} \\cup \\{X = 2\\}) = P(X = 1) + P(X = 2)$. </span>\n\n\n\n## Mean of a Discrete Random Variable\n\n- Suppose $X$ takes values $x_1, \\dots, x_k$ with probabilities $P(X = x_1), \\dots, P(X = x_k)$.\n\n- The **mean** or **expected value** of $X$ is the sum of each outcome multiplied by its corresponding probability:\n$$E(X) := x_1 \\times P(X = x_1) + \\dots + x_k \\times P(X = x_k) = \\sum_{i=1}^kx_iP(X=x_i)$$\n\n- The Greek letter $\\mu$ may be used in place of the notation $E(X)$.\n\n\n::: notes\n- Give an example\n:::\n\n\n. . .\n\n::: alert\n👉 The mean of a discrete random variable $X$ is the **weighted average** of possible values $x$ *weighted by their corresponding probability*.\n:::\n\n. . .\n\n::: question\nWhat is the mean of $X$ (the number of heads) in the previous example?\n:::\n\n. . .\n\n::: question\nWhat about variance of $X$?\n:::\n\n::: notes\n- On average, we will see one heads comes up when we toss a fair coin twice.\n:::\n\n\n## Variance of a Discrete Random Variable {visibility=\"hidden\"}\n\n- Suppose $X$ takes values $x_1, \\dots , x_k$ with probabilities $P(X = x_1), \\dots, P(X = x_k)$ and expected value $\\mu = E(X)$.\n\n- The variance of $X$, denoted by $\\var(X)$ or $\\sigma^2$, is $$\\small \\var(X) := (x_1 - \\mu)^2 \\times P(X = x_1) + \\dots + (x_k - \\mu)^2 \\times P(X = x_k) = \\sum_{i=1}^k(x_i - \\mu)^2P(X=x_i)$$\n\n- The standard deviation of $X$, $\\sigma$, is the square root of the variance.\n\n. . .\n\n::: alert\n👉 The variance of a discrete random variable $X$ is the *weighted sum of squared deviation* from the mean weighted by probability values.\n:::\n\n. . .\n\n::: question\nWhat is the variance of $X$ (the number of heads) in the previous example?\n:::\n\n# Binomial Distribution\n\n## Binomial Experiment and Random Variable\n\n- A **binomial experiment** is the one having the following properties:\n  1. 👉 The experiment consists of a **fixed** number of **identical** trials $n$.\n  \n  2. 👉 Each trial results in one of **exactly two** outcomes (*success* (S) and *failure* (F)).\n  \n  3. 👉 Trials are **independent**, meaning that the outcome of any trial does not affect the outcome of any other trial.\n  \n  4. 👉 The probability of success is **constant** for all trials.\n  \n- If $X$ is defined as  <span style=\"color:blue\"> the number of successes observed in $n$ trials </span>, $X$ is a binomial random variable.\n\n. . .\n\n::: alert\n- The word *success* just means one of the two outcomes, and *does not necessarily mean something good. *\n- 😲 Can define *Drug abuse* as success and *No drug abuse* as failure.\n:::\n\n\n\n::: notes\nif *smoking* and *non-smoking* are the only two outcomes of some binomial experiment.\n:::\n\n\n## Binomial Distribution\n\n- The probability function $P(X = x)$ of a binomial r.v. $X$ can be *fully* determined by \n  + the number of trials $n$\n  + probability of success $\\pi$\n\n- Different $(n, \\pi)$ pairs generate different binomial probability distributions.\n\n- $X$ is said to follow a binomial distribution with **parameters** $n$ and $\\pi$, written as $\\color{blue}{X \\sim binomial(n, \\pi)}$.\n\n. . .\n\n- The binomial probability function is \n$$ \\color{blue}{P(X = x \\mid n, \\pi) = \\frac{n!}{x!(n-x)!}\\pi^x(1-\\pi)^{n-x}, \\quad x = 0, 1, 2, \\dots, n}$$ with mean $\\mu = E(X) = n\\pi$ and variance $\\sigma^2 = \\var(X) = n\\pi(1-\\pi)$.\n\n::: notes\n- Once $(n, \\pi)$ is fixed, we know exactly what the distribution looks like, and we can form a table, graph, and provide a mathematical formula of the binomial distribution.\n:::\n\n. . .\n\n::: question\nTossing a fair coin two times independently. Let $X =$ # of heads. Is $X$ a binomial r.v.?\n:::\n\n\n::: notes\n\n- Example: Toss a fair coin two times independently.\n  + $X =$ # of heads\n  + $X \\sim binomial(n=2, \\pi=1/2)$\n  \n:::\n\n\n<!-- ## [Binomial Distribution Applet](https://math4720-f25.github.io/website/ojs/prob-binomial-ojs.html) -->\n\n<!-- {{< include prob-binomial-ojs.qmd >}} -->\n\n\n\n## Binomial Distribution Example\n\n\n::::: columns\n\n::: {.column width=\"90%\"}\n\nAssume that 20% of all drivers have a blood alcohol level above the legal limit. For a random sample of 15 vehicles, compute the probability that:\n\n  1. **Exactly 6** of the 15 drivers will *exceed* the legal limit.\n  \n  2. Of the 15 drivers, **6 or more** will *exceed* the legal limit.\n  \n:::\n\n::: {.column width=\"10%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/07-distribution/alcohol.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n:::::\n\n\n. . .\n\n- Suppose it is a binomial experiment with $n = 15$ and $\\pi = 0.2$.\n\n- Let $X$ be the number of drivers exceeding limit.\n\n- $X \\sim binomial(15, 0.2)$.\n\n$$ \\color{blue}{P(X = x \\mid n=15, \\pi=0.2) = \\frac{15!}{x!(15-x)!}(0.2)^x(1-0.2)^{15-x}, \\quad x = 0, 1, 2, \\dots, 15}$$\n\n\n::: notes\n\n- On a particular roadway, assume that 20% of all drivers have a blood alcohol level above the legal limit. \n  3. All 15 drivers will have a blood alcohol level *within* the legal limit.\n  \n:::\n\n## Binomial Distribution Example $X \\sim binomial(15, 0.2)$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Binomial Distribution Example\n\n::::: columns\n\n::: {.column width=\"90%\"}\n\nAssume that 20% of all drivers have a blood alcohol level above the legal limit. For a random sample of 15 vehicles, compute the probability that:\n\n  1. Exactly 6 of the 15 drivers will *exceed* the legal limit.\n  \n  2. Of the 15 drivers, 6 or more will *exceed* the legal limit.\n  \n:::\n\n::: {.column width=\"10%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/07-distribution/alcohol.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n:::::\n\n\n::: notes\n- On a particular roadway, assume that 20% of all drivers have a blood alcohol level above the legal limit. \n\n- Suppose it is a binomial experiment with $n = 15$ and $\\pi = 0.2$. \n- Let $X$ be the number of drivers exceeding limit. Then $X \\sim binomial(15, 0.2)$.\n:::\n\n\n. . .\n\n  1. $\\small P(X = 6) = \\frac{n!}{x!(n-x)!}\\pi^x(1-\\pi)^{n-x} = \\frac{15!}{6!(15-6)!}(0.2)^6(1-0.2)^{15-6} = 0.043$\n  \n. . .\n\n  2. $\\small P(X \\ge 6) = p(6) + \\dots + p(15) = 1 - P(X \\le 5) = 1 - (p(0) + p(1) + \\dots + p(5)) = 0.0611$\n  \n\n::: notes\n\n  3. All 15 drivers will have a blood alcohol level *within* the legal limit.\n  3. $\\small P(X = 0) = \\frac{15!}{0!(15-0)!}(0.2)^0(1-0.2)^{15-0} = 0.0352$\n- $P(X \\ge 6) = 1 - P(X \\le 5)$ very useful trick\n- Calculation is super tedious, even you use a calculator!\n\n:::\n\n\n. . .\n\n::: tip\nNever do this by hand. We compute them using R!\n:::\n\n\n## Binomial Example Computation in R\n<!-- - R Shiny app is at [Binomial Calculator](http://sctc.mscs.mu.edu:3838/sample-apps/Calculator/) -->\n- With `size` the number of trials and `prob` the probability of success,\n  + **`dbinom(x, size, prob)`** to compute $P(X = x)$\n  + **`pbinom(q, size, prob)`** to compute $P(X \\le q)$\n  + **`pbinom(q, size, prob, lower.tail = FALSE)`** to compute $P(X > q)$\n  \n::::: columns\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## 1. P(X = 6)\ndbinom(x = 6, size = 15, prob = 0.2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.043\n```\n\n\n:::\n\n```{.r .cell-code}\n## 2. P(X >= 6) = 1 - P(X <= 5)\n1 - pbinom(q = 5, size = 15, prob = 0.2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0611\n```\n\n\n:::\n:::\n\n:::\n\n\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## 2. P(X >= 6) = P(X > 5)\npbinom(q = 5, size = 15, prob = 0.2, \n       lower.tail = FALSE)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0611\n```\n\n\n:::\n:::\n\n:::\n\n:::::\n\n\n## Binomial(15, 0.2)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"false\"}\nplot(x = 0:15, y = dbinom(0:15, size = 15, prob = 0.2), type = 'h', xlab = \"x\", \n     ylab = \"P(X = x)\", lwd = 5, main = \"Binomial(15, 0.2)\")\n```\n\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: notes\n- Since $n = 15$ and $\\pi = 0.2$, mean is 3.\n- Most of the probabilities are around $x = 3$. \n- It's very uncommon to see that more than 10 drivers have alcohol level above the legal limit.\n:::\n\n\n# Poisson Distribution\n\n## Poisson Random Variables\n\n- If we'd like to count **the number of occurrences of some event over a unit of time period or space (region)** and calculate its probability, we could consider the **Poisson distribution**.\n  + Number of COVID patients arriving at ICU in one hour\n  + Number of Marquette students logging onto D2L in one day\n  + Number of dandelions per square meter in Marquette campus\n\n. . .\n\n- Let $X$ be a Poisson r.v. Then $\\color{blue}{X \\sim Poisson(\\lambda)}$, where $\\lambda$ is the parameter representing the **mean** number of occurrences of the event in the interval.\n$$\\color{blue}{P(X = x \\mid \\lambda) = \\frac{\\lambda^x e^{-\\lambda}}{x!}, \\quad x = 0, 1, 2, \\dots}$$ with both mean and variance being equal to $\\lambda$.\n\n\n::: notes\n- Let $X$ be a Poisson r.v. representing the number of occurrences of some event over a unit of interval (time, space, volume).\n:::\n\n## Assumptions and Properties of Poisson Variables\n\n- 👉 **Events occur one at a time**; two or more events do not occur at the same time or in the same space or spot.\n\n- 👉 The occurrence of an event in a given period of time or region of space is **independent** of the occurrence of the event in a **nonoverlapping** time period or region of space.\n\n- 👉 $\\lambda$ is **constant** of any period or region.\n\n::: notes\n- You cannot say two patients arrived at ICU at the same time.\n- You can always know which patient arrives at ICU earlier.\n- You can always know which students log in D2L earlier\n:::\n\n\n. . .\n\n::: question\nCan you find the difference between binomial and Poisson distributions?\n:::\n\n\n. . .\n\n- The Poisson distribution\n  + is determined by one single parameter $\\lambda$\n  + has possible values $x = 0, 1, 2, \\dots$ with no upper limit (countable), while a binomial variable has possible values $0, 1, 2, \\dots, n$ (finite)\n\n\n<!-- ## [Poisson Distribution Applet](https://math4720-f25.github.io/website/ojs/prob-poisson-ojs.html) -->\n\n<!-- {{< include prob-poisson-ojs.qmd >}} -->\n\n\n\n## Poisson Distribution Example\n\n\n\n::::: columns\n\n::: {.column width=\"90%\"}\nLast year there were 4200 births at the University of Wisconsin Hospital. Assume $X$ be the number of births in a given day at the center, and $X \\sim Poisson(\\lambda)$. Find\n\n  1. $\\lambda$, the mean number of births **per day**.\n  2. the probability that on a randomly selected day, there are exactly 10 births.\n  3. $P(X > 10)$? \n  \n:::\n\n::: {.column width=\"10%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/07-distribution/baby.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n:::::\n\n. . .\n\n1. $\\small \\lambda = \\frac{\\text{Number of birth in a year}}{\\text{Number of days}} = \\frac{4200}{365} = 11.5$\n\n. . .\n\n2. $\\small P(X = 10 \\mid \\lambda = 11.5) = \\frac{\\lambda^x e^{-\\lambda}}{x!} = \\frac{11.5^{10} e^{-11.5}}{10!} = 0.113$\n\n. . .\n\n3. $\\small P(X > 10) = p(11) + p(12) + \\cdots + p(20) + \\cdots$ (No end!)\n$\\small P(X > 10) = 1 - P(X \\le 10) = 1 - (p(0) + p(1) + p(2) + \\dots + p(10))$.\n\n::: notes\n.tip[\nI know you are waiting for R implementation!\n:::\n\n\n## Poisson Example Compuatation in R\n\n<!-- - R Shiny app is at [Poisson Calculator](http://sctc.mscs.mu.edu:3838/sample-apps/Calculator/) -->\n<!-- P(X <= 10) = 0.392 -->\n- With `lambda` the mean of Poisson distribution, \n  + **`dpois(x, lambda)`** to compute $P(X = x)$\n  + **`ppois(q, lambda)`** to compute $P(X \\le q)$\n  + **`ppois(q, lambda, lower.tail = FALSE)`** to compute $P(X > q)$\n\n::::: columns\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(lam <- 4200 / 365)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.5\n```\n\n\n:::\n\n```{.r .cell-code}\n## P(X = 10)\ndpois(x = 10, lambda = lam)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.113\n```\n\n\n:::\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## P(X > 10) = 1 - P(X <= 10)\n1 - ppois(q = 10, lambda = lam)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.599\n```\n\n\n:::\n\n```{.r .cell-code}\n## P(X > 10)\nppois(q = 10, lambda = lam, \n      lower.tail = FALSE) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.599\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n\n\n## Poisson(11.5)\n\n- $X$ has no upper limit. The graph is *truncated* at $x = 24$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\npar(mar = c(3.8, 3.8, 1, 0), mgp = c(2.5, 0.5, 0))\nplot(0:24, dpois(0:24, lambda = lam), type = 'h', lwd = 5, las = 1,\n     ylab = \"P(X = x)\", xlab = \"x\", main = \"Poisson(11.5)\")\n```\n\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n# [Continuous Probability Distributions]{.orange}{background-image=\"./images/07-distribution/Gauss.jpg\" background-size=\"cover\" background-position=\"50% 50%\" background-color=\"#447099\"}\n\n\n## Continuous Probability Distributions\n\n- A continuous r.v. can take on **any** values from *an interval of the real line*.\n\n- Instead of probability functions, a continuous r.v. $X$ has the **probability density function (pdf)** $f(x)$ such that for any real value $a < b$,\n$$P(a < X < b) = \\int_{a}^b f(x) dx$$\n\n<!-- - The **cumulative distribution function (cdf)** of $X$ is defined as -->\n<!-- $$F(x) := P(X \\le x) = \\int_{-\\infty}^x f(t)dt$$ -->\n\n. . .\n\n- Every pdf must satisfy <span style=\"color:blue\"> (1) $f(x) \\ge 0$ for all $x$; (2) $\\int_{-\\infty}^{\\infty} f(x) dx = 1$ </span>\n\n. . .\n\n😎 Luckily we don't deal with integrals in this course.\n\n\n## Density Curve\n\n- A pdf generates a graph called the **density curve** that shows the *likelihood* of a random variable at all possible values.\n\n- $P(a < X < b) = \\int_{a}^b f(x) dx$: **The area under the density curve between $a$ and $b$.**\n\n- $\\int_{-\\infty}^{\\infty} f(x) dx = 1$: **The total area under any density curve is equal to 1.**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n::: notes\n- ** $P(a < X < b)$ is the area under the density curve between $a$ and $b$.**\n- **The total area under any density curve is equal to 1.**\n:::\n\n\n## Commonly Used Continuous Distributions\n\n- [Distribution Applet](https://homepage.divms.uiowa.edu/~mbognar/)\n\n- In this course, we will touch **normal (Gaussian)**, **Student's t**, **chi-squared**, **F**\n\n- Some other common distributions include **uniform**, **exponential**, **gamma**, **beta**, **inverse gamma**, **Cauchy**, etc. (MATH 4700)\n\n\n## Normal (Gaussian) Distribution\n\n-  The normal distribution, $N(\\mu, \\sigma^2$), has the pdf given by\n$$\\small f(x) = \\frac{1}{\\sqrt{2\\pi}\\sigma}e^{\\frac{-(x-\\mu)^2}{2\\sigma^2}}, \\quad -\\infty < x < \\infty$$\n    + Two parameters mean $\\mu$ and variance $\\sigma^2$ (standard deviation $\\sigma$)\n    + Always bell shaped, and symmetric about the mean $\\mu$\n    + When $\\mu = 0$ and $\\sigma = 1$, $N(0, 1)$ is called **standard normal**.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Normal Density Curves\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n<!-- ## [Normal Distribution Applet](https://math4720-f25.github.io/website/ojs/prob-normal-ojs.html) -->\n\n<!-- {{< include prob-normal-ojs.qmd >}} -->\n\n\n## Standardization and Z-Scores\n\n- **Standardization**: Convert $N(\\mu, \\sigma^2)$ to $N(0, 1)$.\n\n- **Why standardization**: Put data onto a *standardized scale*, making comparisons easier!\n\n. . .\n\n::: question\n\n|Measure         | SAT               | ACT         |\n|:-------------:|:-----------------:|:------------:|\n| Mean          | 1100              | 21          |  \n| SD            | 200               | 6           |\n\n- The distribution of SAT and ACT scores are both nearly normal.\n\n- Suppose Anna scored 1300 on her SAT and Tommy scored 24 on his ACT. Who performed better?\n\n:::\n\n::: midi\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/07-distribution/sat_act.jpeg){fig-align='center' width=50%}\n:::\n:::\n\n:::\n\n::: notes\n- For normal distribution, we usually do the so-called Standardization.\n- The idea is to Make a normal distribution standard normal, i.e., convert $N(\\mu, \\sigma^2)$ to $N(0, 1)$.\n- But why do we want to do that?\n- Well, by doing so, we can put any data onto a *standardized scale*, making comparisons easier and reasonable.\n- The distribution of SAT and ACT scores are both nearly normal. \n- Suppose Anna scored 1300 on her SAT and Tommy scored 24 on his ACT. Who performed better?\n- It's hard to compare the two scores, right? because they are on the different scales.\n- And standardization helps us compare Anna and Tommy's performance because we are gonna put their scores on the same scale. Let's see how.\n:::\n\n\n## Standardization and Z-Scores\n\n-  If $x$ is an observation from a distribution with mean $\\mu$ and standard deviation $\\sigma$, the standardized value of $x$ is so-called **$z$-score**:\n$$z = \\frac{x - \\mu}{\\sigma}$$\n\n. . .\n\n- A $z$-score tells us how many standard deviations $x$ falls away from the mean, and in which direction.\n  + Observations **larger (smaller)** than the mean have **positive (negative)** $z$-scores.\n  + A $z$-score -1.2 means that $x$ is 1.2 standard deviations to the **left** of (**below**) the mean.\n  + A $z$-score 1.8 means that $x$ is 1.8 standard deviations to the **right** of (**above**) the mean.\n\n. . .\n\n- <span style=\"color:blue\">  If $X \\sim N(\\mu, \\sigma^2)$, $Z = \\frac{X - \\mu}{\\sigma}$ follows the standard normal distribution, i.e., $Z \\sim N(0, 1)$. </span>\n\n\n::: notes\n\n- If z-score is positive, it means that the original x is greater the mean.\n- Since we divided by sigma, the standardized value is measured using SD as the unit.\n- A $z$-score tells us how many standard deviations the original observation $x$ falls away from the mean, and in which direction.\n  + Observations **larger (smaller)** than the mean have **positive (negative)** $z$-scores.\n  + A $z$-score -1.2 means that $x$ is 1.2 standard deviations to the **left** of (**below**) the mean.\n  + A $z$-score 1.8 means that the original observation $x$ is 1.8 standard deviations to the **right** of (**above**) the mean.\n- <span style=\"color:blue\">  If $X \\sim N(\\mu, \\sigma^2)$, $Z = \\frac{X - \\mu}{\\sigma}$ follows the standard normal distribution, i.e., $Z \\sim N(0, 1)$. </span>\n\n:::\n\n\n\n## Standardization Illustration\n\n- $X - \\mu$ shifts the mean from $\\mu$ to 0\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=56%}\n:::\n:::\n\n\n. . .\n\n- $\\frac{X - \\mu}{\\sigma}$ scales the variation from 4 to 1\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=56%}\n:::\n:::\n\n\n\n## Standardization Illustration\n\n- A value of $x$ that is 2 standard deviation below $\\mu$ corresponds to $z = -2$.\n\n- $z = \\frac{x  -\\mu}{\\sigma} \\iff x = \\mu + z\\sigma$. If $z = -2$, $x = \\mu - 2\\sigma$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## SAT and ACT Example\n\n- $z_{A} = \\frac{x_{A} - \\mu_{SAT}}{\\sigma_{SAT}} = \\frac{1300-1100}{200} = 1$; $z_{T} = \\frac{x_{T} - \\mu_{ACT}}{\\sigma_{ACT}} = \\frac{24-21}{6} = 0.5$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: notes\n- After standardizing SAT and ACT distributions, we can compare SAT and ACT scores together.\n- The z-score for Anna is 1, so her SAT score is 1 SD above the mean of SAT.\n- The z-score for Tommy is 0.5, so his ACT score is 0.5 SD above the mean of ACT.\n- Originally, SAT and ACT are two different distributions with different scales.\n- But now we convert both distributions to standard normal distributions, so that they can be compared.\n- Because Anna's score is 1 sd higher than the mean, and Tommy's socre is 0.5 sd higher than the mean, we conclude that Anna performed better on the test.\n\nAn observation x1 is said to be more unusual than another observation x2 if the absolute value of its Zscore is larger than the absolute value of the other observation's Z-score.\n:::\n\n\n## Finding Tail Areas $P(X < x)$\n\n::: question\nWhat fraction of students have an SAT score below Anna's score of 1300?\n:::\n\n- This is the same as the percentile Anna is at, which is the percentage of cases that have lower scores than Anna.\n\n- Need $P(X < 1300 \\mid \\mu = 1100, \\sigma = 200)$ or $P(Z < 1 \\mid \\mu = 0, \\sigma = 1)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/tail-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n::: notes\n\n- If there are 100 test takers, how many students score are lower than Anna's score?\nIt's very useful in statistics to be able to identify tail areas of distributions. For instance, what\nfraction of people have an SAT score below Anna's score of 1300? This is the same as the percentile\nAnna is at, which is the percentage of cases that have lower scores than Anna. We can visualize such\na tail area like the curve and shading shown in Figure 4.6.\n- The area to the left of Z represents the fraction of people who scored\nlower than Anna.\n\n:::\n\n\n\n\n## Finding Tail Areas $P(X < x)$ in R\n\n- With **`mean`** and **`sd`** representing the mean and standard deviation of a normal distribution\n  + **`pnorm(q, mean, sd)`** to compute $P(X \\le q)$\n  + **`pnorm(q, mean, sd, lower.tail = FALSE)`** to compute $P(X > q)$\n\n. . .\n\n\n::::: columns\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-23-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(1, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.841\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(1300, mean = 1100, sd = 200)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.841\n```\n\n\n:::\n:::\n\n\n- The shaded area represents the proportion 84.1% of SAT test takers who had z-score below 1.\n\n\n:::\n\n:::::\n\n\n::: notes\n- Don't forget R Shiny app is at [Normal Calculator](http://sctc.mscs.mu.edu:3838/sample-apps/Calculator/)\n- The default values of `mean` and `sd` are 0 and 1 respectively, i.e., $N(0, 1)$.\n- It is rarely used in practice, but you can find tail areas using the normal table (Table 1 in the textbook.) \n:::\n\n\n## SAT Example Cont'd {visibility=\"hidden\"}\n\n- SAT score follows $N(1100, 200^2)$. Shannon is a SAT taker, and nothing is known about Shannon's SAT aptitude. What is the probability Shannon SAT scores at least 1190?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## SAT Example Cont'd\n\n- SAT score follows $N(1100, 200^2)$. Shannon is a SAT taker, and nothing is known about Shannon's SAT aptitude. What is the probability Shannon SAT scores **at least** 1190?\n\n::::: columns\n\n::: {.column width=\"50%\"}\n\n- <span style=\"color:red\"> Step 1: State the problem </span>\n  +  <span style=\"color:blue\"> We like to compute $P(X \\ge 1190)$. </span>\n  \n- <span style=\"color:red\"> Step 2: Draw a picture\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-26-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n- <span style=\"color:red\"> Step 3: Find the area\n\nWe want the **upper tail** area, so `lower.tail = FALSE`!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(q = 1190, mean = 1100, sd = 200, \n      lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.326\n```\n\n\n:::\n:::\n\n\n:::\n\n:::::\n\n\n\n\n## SAT Example Cont'd {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- <span style=\"color:red\"> Step 3: Find $z$-score </span>: \n  + <span style=\"color:blue\"> $z = \\frac{1190 - 1100}{200} = 0.45$ and we like to compute $P(X > 1190) = P\\left( \\frac{X - \\mu}{\\sigma} > \\frac{1190 - 1000}{200} \\right) = P(Z > 0.45) = 1 - P(Z \\le 0.45)$ </span>\n  \n- <span style=\"color:red\"> Step 4: Find the area using `pnorm()` </span>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n1 - pnorm(0.45)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.326\n```\n\n\n:::\n:::\n\n\n\n## Normal Percentiles in R\n\n- To get the $100p$-th percentile (or the $p$-quantile $q$), given probability $p$, we use\n  + **`qnorm(p, mean, sd)`** to get a value of $X$, $q$, such that $P(X \\le q) = p$ \n  + **`qnorm(p, mean, sd, lower.tail = FALSE)`** to get $q$ such that $P(X \\ge q) = p$\n\n::: notes\n- We may be also interested in the value of $X$ given a probability or percentage. \n- In other words, we'd like to find the $100p$-th percentile given the probability $p$.\n\n  <!-- <footnote> The formal definition of the quantile function is $Q(p) := \\inf\\{x \\in \\mathbf{R}: P(X \\le x) \\ge p\\}$. </footnote> -->\n:::\n\n\n## SAT Example\n\nWhat is the 95th percentile for SAT scores?\n\n::: alert\n**Find a value $q$ of the normal random variable, not an area (probability), which is 0.95.**\n:::\n\n\n::::: columns\n\n::: {.column width=\"55%\"}\n\n- <span style=\"color:red\"> Step 1: State the problem </span>\n  +  <span style=\"color:blue\"> Find a variable's value $q$ s.t $P(X < q) = 0.95$. </span>\n  \n- <span style=\"color:red\"> Step 2: Draw a picture\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-30-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\n\n::: {.column width=\"45%\"}\n\n- <span style=\"color:red\"> Step 3: Find the quantile\n\nWe want the **q**uantile, so use `qnorm()`!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(p = 0.95, mean = 1100, sd = 200)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1429\n```\n\n\n:::\n:::\n\n\n:::\n\n:::::\n\n\n## SAT Example Cont'd {visibility=\"hidden\"}\n\n- <span style=\"color:red\"> Step 3: Find $z$-score s.t. $P(Z < z) = 0.95$ using `qnorm()`</span>: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(z_95 <- qnorm(0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.64\n```\n\n\n:::\n:::\n\n\n- <span style=\"color:red\"> Step 4: Find the $x$ of the original scale </span>\n  + <span style=\"color:blue\"> $z_{0.95} = \\frac{x-\\mu}{\\sigma}$. So $x = \\mu + z_{0.95}\\sigma$. </span>\n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(x_95 <- 1100 + z_95 * 200)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1429\n```\n\n\n:::\n:::\n\n\n- The 95th percentile for SAT scores is 1429.\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(p = 0.95, mean = 1100, sd = 200)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1429\n```\n\n\n:::\n:::\n\n\n\n<!-- ## Finding Probabilties -->\n\n<!-- 👉 **Draw and label the normal curve and shade the area of interest.** -->\n\n<!-- - 👉 **Less than** -->\n<!--   + $\\small P(X < x) = P(Z < z)$ -->\n<!--   + `pnorm(z)` -->\n<!--   + `pnorm(x, mean = mu, sd = sigma)` -->\n\n<!-- - 👉 **Greater than** -->\n<!--   + $\\small P(X > x) = P(Z > z) = 1 - P(Z \\le z)$ -->\n<!--   + `1 - pnorm(z)` -->\n\n<!-- ::: alert -->\n<!-- - 👉 Standardization is not a must.  -->\n<!-- - 👉 We have to specify the mean and SD of the original distribution of $X$, like `pnorm(x, mean = mu, sd = sigma)`. -->\n<!-- ::: -->\n\n\n\n## Finding Probabilties {visibility=\"hidden\"}\n\n👉 **Draw and label the normal curve and shade the area of interest.**\n\n- 👉 **Less than**\n  + $\\small P(X < x) = P(Z < z)$\n  + `pnorm(z)`\n  + `pnorm(x, mean = mu, sd = sigma)`\n\n- 👉 **Greater than**\n  + $\\small P(X > x) = P(Z > z) = 1 - P(Z \\le z)$\n  + `1 - pnorm(z)`\n\n::: alert\n\n- 👉 Standardization is not a must.\n\n- 👉 We have to specify the mean and SD of the original distribution of $X$, like `pnorm(x, mean = mu, sd = sigma)`.\n\n:::\n\n\n\n\n## Finding Probabilties {visibility=\"hidden\"}\n\n- 👉 **Between two numbers**\n  + $\\small P(a < X < b) = P(z_a < Z < z_b) = P(Z < z_b) - P(Z < z_a)$\n  + `pnorm(z_b) - pnorm(z_a)`\n\n- 👉 **Outside of two numbers** $(a < b)$\n$$\\small \\begin{align} P(X < a \\text{ or } X > b) &= P(Z < z_a \\text{ or } Z > z_b) \\\\ &= P(Z < z_a) + P(Z > z_b) \\\\ &= P(Z < z_a) + 1 - P(Z < z_b) \\end{align}$$\n  + `pnorm(z_a) + 1 - pnorm(z_b)`\n  + `pnorm(z_a) + pnorm(z_b, lower.tail = FALSE)`\n\n\n::: alert\n\n- 👉 Any probability can be computed using the *\"less than\"* form (*lower* or *left* tail).\n\n- 👉 If the calculation involves the \"greater than\" form, add `lower.tail = FALSE` in `pnorm()`.\n\n:::\n\n\n## Checking Normality: Normal Quantile Plot {visibility=\"hidden\"}\n\n- Many statistical methods assume variables are normally distributed.\n\n- Testing the appropriateness of the normal assumption is a key step.\n\n- A **normal quantile plot (normal probability plot)** or a **Quantile-Quantile plot (QQ plot)** helps us check normality assumption.\n  + $X$-axis: Quantiles of the *ordered* data if the data were normally distributed.\n  + $Y$-axis: *Ordered* data values\n\n- If the data are like normally distributed, the points on the QQ plot will lie close to a **straight line**.\n\n\n\n\n::: notes\n\n- Many statistical methods assume variables are normally distributed.\n- Testing the appropriateness of the normal assumption is a key step in many data analyses.\n- A **normal quantile plot (normal probability plot)** or a **Quantile-Quantile plot (QQ plot)** consists of a plot of the **ordered data** on the Y-axis and the $z$-scores associated with order of the observations on the X-axis. \n- If the distribution of the data is close to a normal distribution, the plotted points on the QQ plot will lie close to a **straight line**.\n\n:::\n\n\n## QQ plot in R {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(normal_sample, main = \"Normal data\", col = 4)\nqqline(normal_sample)\nqqnorm(right_skewed_sample, main = \"Right-skewed data\", col = 6)\nqqline(right_skewed_sample)\n```\n\n::: {.cell-output-display}\n![](07-distribution_files/figure-revealjs/unnamed-chunk-35-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n",
    "supporting": [
      "07-distribution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}