{
  "hash": "59fceb5e1f252227c2d9275c65947db5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Simple Linear Regression `<svg aria-hidden=\"true\" role=\"img\" viewBox=\"0 0 512 512\" style=\"height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:currentColor;overflow:visible;position:relative;\"><path d=\"M64 64c0-17.7-14.3-32-32-32S0 46.3 0 64V400c0 44.2 35.8 80 80 80H480c17.7 0 32-14.3 32-32s-14.3-32-32-32H80c-8.8 0-16-7.2-16-16V64zm406.6 86.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L320 210.7l-57.4-57.4c-12.5-12.5-32.8-12.5-45.3 0l-112 112c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L240 221.3l57.4 57.4c12.5 12.5 32.8 12.5 45.3 0l128-128z\"/></svg>`{=html}'\ntitle-slide-attributes:\n  data-background-image: ../images/bg.png\n  # data-background-size: stretch\n  # data-slide-number: none\nformat: \n  live-revealjs: \n    output-file: 04-slr-f26-slides.html\n    code-line-numbers: true\nwebr:\n  cell-options:\n    autorun: false\n  # packages:\n  #   - tidyverse\n---\n\n\n#  {visibility=\"hidden\"}\n\n\\def\\bx{\\mathbf{x}}\n\\def\\bg{\\mathbf{g}}\n\\def\\bw{\\mathbf{w}}\n\\def\\bbeta{\\boldsymbol \\beta}\n\\def\\bX{\\mathbf{X}}\n\\def\\by{\\mathbf{y}}\n\\def\\bH{\\mathbf{H}}\n\\def\\bI{\\mathbf{I}}\n\\def\\bS{\\mathbf{S}}\n\\def\\bW{\\mathbf{W}}\n\\def\\T{\\text{T}}\n\\def\\cov{\\mathrm{Cov}}\n\\def\\cor{\\mathrm{Corr}}\n\\def\\var{\\mathrm{Var}}\n\\def\\E{\\mathrm{E}}\n\\def\\bmu{\\boldsymbol \\mu}\n\\DeclareMathOperator*{\\argmin}{arg\\,min}\n\\def\\Trace{\\text{Trace}}\n\n\n\n<!-- #| echo: true -->\n<!-- #| output.lines: !expr c(5:7) -->\n<!-- (wls_fit <- lm(ex5_5$sales ~ ex5_5$expense,  -->\n<!--                weights = wt)) -->\n               \n<!-- # Conditional Thinking -->\n\n## Explore Conditional Relationships\n\n<!-- ::: {.columns} -->\n<!-- ::: {.column width=\"52%\"} -->\n\nRegression is a tool for making **conditional statements**:\n\n> What should we expect for $Y$ when $X = x$?\n\n. . .\n\n::: alert\n\n**Example.** *What highway miles per gallon (MPG) ($Y$) should we expect for a car with an engine displacement ($X$) of 3 liters?*\n\n:::\n\nWe wanna learn **how $Y$ varies or changes with values of $X$**, not the other way around.\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: midi\n\n| $Y$ | $X$ |\n|:---------:|:---------:|\n| Response variable| Predictor |\n| Outcome variable | Covariate |\n| Dependent variable | Independent variable |\n| Output variable | Input variable |\n| Endogenous variable | Exogenous variable |\n| Target variable | Explanatory variable |\n| Label | Feature |\n| Regressand | Regressor |\n| ...  | ... |\n\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n::: fragment\n\n::: midi\n\n| Instead of Asking | Better to Ask |\n|:--------------|:------------|\n| Are $X$ and $Y$ related? | [How does $Y$ vary across values of $X$?]{.red} |\n\n:::\n\n:::\n\n:::\n\n::::\n\n::: notes\n\nWeek 1 already introduced regression broadly. This slide narrows the focus: simple linear regression is about conditional thinking, not just drawing a line.\n\n:::\n\n\n<!-- ::: -->\n<!-- ::: {.column width=\"48%\"} -->\n## {visibility=\"hidden\"}\n\n\n| Instead of Asking | Better to Ask |\n|------------|------------|\n| Are $X$ and $Y$ related? | How does $Y$ vary across values of $X$? |\n| Is the slope significant? | Is the estimated change meaningful? |\n| What is the best line? | Is a line useful for this question? |\n\n<!-- ::: -->\n<!-- ::: -->\n\n\n##  (Linear) Regression Workflow\n\n| Step | Question | Main tool |\n|-----|----------|------|\n| 1. Question | Prediction, description, comparison, or causal claim? | Context |\n| 2. Data | What do the variables actually measure? | Scatterplot |\n| 3. Fit | What line summarizes the pattern? | Least squares/Maximum likelihood |\n| 4. Uncertainty | How stable is the fitted line? | Simulation / Intervals |\n| 5. Prediction | Mean response or one new observation? | Prediction bands |\n| 6. Check | What does the line miss? | Residuals / Sensitivity |\n\n\n## What Research Questions Can Regression Answer\n\n| Step | Question | Main tool |\n|-----|----------|------|\n| 1. Question | Prediction, description, comparison, or causal claim? | Context |\n\n. . .\n\n| Goal | MPG Example |\n|-----|---------|\n| Prediction | What highway MPG for a 3-liter engine? |\n| Description | How does MPG vary with engine size? | \n| Comparison | How do automatic and manual transmissions differ in MPG? |\n| Causal inference | Would changing $X$ change $Y$? |\n\n. . .\n\n::: danger\nCausal inference requires a carefully designed study and additional assumptions.\n:::\n\n. . .\n\n::: {.callout-note style=\"font-size: 1.2em\"}\n\nDescription and comparison are **inferential** goals.\n\n:::\n\n \n::: notes\n\n| Goal | Example question | Safe wording |\n|-----|---------|--------|\n| Prediction | What highway MPG for a 3-liter engine? | We predict... |\n| Description | How does MPG vary with engine size? | MPG is associated with... |\n| Comparison | How do auto and manual transmission differ in MPG? | The group difference is... |\n| Causal inference | Would changing $X$ change $Y$? | With careful design of experiment and assumptions |\n\n:::\n\n<!-- ##  (Linear) Regression Workflow -->\n\n<!-- | Step | Question | Main tool | -->\n<!-- |-----|----------|------| -->\n<!-- | 1. Question | Prediction, description, comparison, or causal claim? | Context | -->\n<!-- | 1. Question | How can engine displacement help us describe or predict highway MPG? | Scatterplot | -->\n\n\n\n<!-- | Step           | MPG example                                                          | Main conclusion                                                                              | -->\n<!-- | ----------------- | -------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- | -->\n<!-- | 1. Question    | How can engine displacement help us describe or predict highway MPG? | The analysis is predictive/descriptive, not automatically causal.                            | -->\n\n\n<!-- ## Practical Regression Workflow -->\n\n<!-- | Step           | MPG example                                                          | Main conclusion                                                                              | -->\n<!-- | ----------------- | -------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- | -->\n<!-- | 1. Question    | How can engine displacement help us describe or predict highway MPG? | The analysis is predictive/descriptive, not automatically causal.                            | -->\n<!-- | 2. Data        | Plot `hwy` against `displ` for the 234 configurations in `ggplot2::mpg`.               | Larger engines generally have lower MPG, but the pattern has clusters and curvature. | -->\n<!-- | 3. Fit         | `lm(hwy ~ displ, data = mpg)`.                                   | Each additional liter is associated with about 3.53 fewer highway MPG, on average.           | -->\n<!-- | 4. Uncertainty | Simulate repeated fitted lines and report the slope interval.        | The line would vary across samples; the slope interval is [-3.91,-3.15].     | -->\n<!-- | 5. Prediction  | Predict highway MPG for a 3.0-liter configuration.                   | The mean MPG is estimated precisely, but one new car is much less predictable.         | -->\n<!-- | 6. Check       | Examine residual curvature and influential observations.             | The line is a useful summary, but it misses systematic structure.                            | -->\n\n\n## Make The Question Concrete\n\nPrediction: [What highway MPG for a 3-liter engine?]{.blue}\n\n\n::: {.columns}\n\n::: {.column width=\"40%\"}\n\n::: midi\n\n| Target | Meaning |\n|------|---|\n| Point prediction | One number for MPG |\n| Interval prediction | A range of values for MPG |\n| Mean response | Average MPG among cars like this |\n| New observation | MPG for one future car |\n| Generalization | Cars like those in the dataset? |\n\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/mpg-new-car-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n:::\n\n\n##  Data\n\n| Step | Question | Main tool |\n|-----|----------|------|\n| 2. Data | What do the variables actually measure? | Scatterplot |\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nlibrary(ggplot2)\nmpg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` my_class800\n# A tibble: 234 × 11\n   manufacturer model      displ  year   cyl trans drv     cty   hwy fl    class\n   <chr>        <chr>      <dbl> <int> <int> <chr> <chr> <int> <int> <chr> <chr>\n 1 audi         a4           1.8  1999     4 auto… f        18    29 p     comp…\n 2 audi         a4           1.8  1999     4 manu… f        21    29 p     comp…\n 3 audi         a4           2    2008     4 manu… f        20    31 p     comp…\n 4 audi         a4           2    2008     4 auto… f        21    30 p     comp…\n 5 audi         a4           2.8  1999     6 auto… f        16    26 p     comp…\n 6 audi         a4           2.8  1999     6 manu… f        18    26 p     comp…\n 7 audi         a4           3.1  2008     6 auto… f        18    27 p     comp…\n 8 audi         a4 quattro   1.8  1999     4 manu… 4        18    26 p     comp…\n 9 audi         a4 quattro   1.8  1999     4 auto… 4        16    25 p     comp…\n10 audi         a4 quattro   2    2008     4 manu… 4        20    28 p     comp…\n# ℹ 224 more rows\n```\n\n\n:::\n:::\n\n\n\n\n::: notes\n\n::: {.callout-note style=\"font-size: 1.2em\"}\n\nIn `R`, use `?mpg` to view information about the data set.\n\n:::\n\n:::\n\n\n<!-- # A regression question -->\n\n##\n\n\n| Step | Question | Main tool |\n|-----|----------|------|\n| 2. Data | What do the variables actually measure? | Scatterplot |\n\n| Step           | MPG example                                                          | Main conclusion                                                                              |\n| ----------------- | -------------------------------------------------------------------- | ------------------------------------------------------------------------------------------|\n| 2. Data        | Plot `hwy` against `displ` for the 234 configurations in `ggplot2::mpg`. | Larger engines generally have lower MPG, but the pattern has clusters and curvature.|\n\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n\n::: midi\n\n| Element                | Meaning                                       |\n| ---------------------- | --------------------------------------------- |\n| unit               | One vehicle                                   |\n| $X=\\texttt{displ}$     | Engine displacement, in liters                |\n| $Y=\\texttt{hwy}$      | EPA highway fuel economy, in miles per gallon |\n| Sample                 | 234 configurations from 38 vehicle models     |\n| Model years            | 1999 and 2008                                 |\n\n:::\n\n:::\n\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/mpg-scatter-start-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Fitting\n\n| Step | Question | Main tool |\n|-----|----------|------|\n| 3. Fit | What line summarizes the pattern? | Least squares/Maximum likelihood |\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/mpg-line-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n. . .\n\n<!-- Before finding the pattern that is most consistent with our data, we need a **model the fitting method applies to**. -->\n\nTo find the pattern most consistent with our data, we first need to specify the model being fitted.\n\n\n# Simple Linear Regression Model\n\n## Simple Linear Regression\n\n::: {.columns}\n::: {.column width=\"45%\"}\n\nFor the $i$-th unit in the target population,\n\n$$\n\\begin{align}\nY_i &= f(X_i) + \\epsilon_i\\\\ &= \\beta_0 + \\beta_1 X_i + \\epsilon_i\n\\end{align}\n$$\n\n- $Y_i$: the response (random) variable\n- $X_i$: **known fixed** value of the predictor\n- $\\epsilon_i$: random error with $\\epsilon_i \\stackrel{iid}{\\sim} N(0, \\sigma^2)$\n<!-- - $\\beta_0$ and $\\beta_1$ are model coefficients. -->\n\n\n\n| Piece | Meaning |\n|---|---|\n| $\\beta_0 + \\beta_1 X_i$ | systematic part |\n| $\\epsilon_i$ | deviation from the pattern |\n| $\\sigma$ | typical vertical scatter |\n\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/model-story-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n<!-- - $\\beta_0$, $\\beta_1$ and $\\sigma^2$ are **fixed unknown parameters** to be estimated from our collected data. -->\n\n- $\\beta_0$, $\\beta_1$, and $\\sigma^2$ are **fixed but unknown parameters** to be estimated from the observed data.\n\n:::\n\n:::\n\n\n\n\n::: notes\nthe *measurement error* model is\n:::\n\n\n## Regression Models a Conditional Distribution\n\nEach time we collect a data set, we obtain a different realization because of **random variation**.\n\n<!-- # ```{r} -->\n<!-- # knitr::include_graphics(\"./images/04-slr/regression_line_data.png\") -->\n<!-- # ``` -->\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Regression Models a Conditional Distribution\n\nEach time we collect a data set, we obtain a different realization because of **random variation**.\n\n<!-- # ```{r} -->\n<!-- # knitr::include_graphics(\"./images/04-slr/regression_line_data.png\") -->\n<!-- # ``` -->\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Regression Models a Conditional Distribution\n\n<!-- When we collect data $\\{ (x_1, y_1), (x_2, y_2), \\dots, (x_n, y_n)\\},$ $y$ is assumed drawn from a normal distribution **conditional on the value of $x$**. Its value varies around its **conditional mean $\\mu_{y \\mid x}$**. -->\n\nFor data $\\{(x_1,y_1),(x_2,y_2),\\dots,(x_n,y_n)\\}$, each response $Y_i$ is assumed to be drawn from a normal distribution **conditional on $X_i=x_i$**. The response varies around its **conditional mean $\\mu_{Y\\mid X=x}$**.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- The **mean response** of $Y$, $\\mu_{Y\\mid X}=E(Y\\mid X)$, has a **straight-line** relationship with $X$, given by the population regression line $\\mu_{Y\\mid X}=\\beta_0+\\beta_1X$.\n\n- The conditional variance of $Y$ does not depend on $X$.\n\n\n\n::: notes\nWith the model, our first job is to collect data and estimate the unknown parameters $\\beta_0$, $\\beta_1$ and $\\sigma^2$!\n:::\n\n\n\n## Model Assumptions\n\n| Assumption | Model statement | What to check visually |\n|-----|---------|------|\n| Conditional mean | $E(Y\\mid X=x)$ is approximately linear | Curved pattern? |\n| Variability | Spread around the line is similar across $X$ | Fan shape? |\n| Independence | Rows provide distinct information | Clustering in groups, time, or space? |\n| Distribution | Residuals are approximately normal | Strong skewness or heavy tails? |\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: notes\n\nDo not present assumptions as a single all-or-nothing checklist. The mean model is usually the first priority for interpretation; dependence is often the first priority for uncertainty.\n\n:::\n\n\n\n# Parameter Estimation and Model Fitting\n\n## Idea of Fitting\n\n- Interested in $\\beta_0$ and $\\beta_1$ in the *sample* regression model:\n\n\\begin{align*}\ny_i &= f(x_i) +  \\epsilon_i \\\\\n    &= \\beta_0 + \\beta_1~x_{i} + \\epsilon_i,\n\\end{align*}\nor\n\n$$E(y_i \\mid x_i) = \\mu_{y|x_i} = \\beta_0 + \\beta_1~x_{i}$$\n\n. . .\n\n- Use sample statistics $b_0$ and $b_1$, computed from the data, to estimate $\\beta_0$ and $\\beta_1$.\n\n- $\\hat{y}_{i}=b_0+b_1x_i$ is the **fitted value** at $x_i$. It estimates the conditional mean $\\mu_{Y\\mid X=x_i}$ and also serves as the point prediction for an individual response at $x_i$.\n\n<!-- - $\\hat{y}_{i} = b_0 + b_1~x_{i}$ predicted value -->\n\n\n\n\n\n::: notes\n\n- OK. once we collect the data, we have a sample regression model.\n- Here I use small x and y to represent the collected data.\n- Given this model, we're interested in $\\beta_0$ (population parameter for the intercept) and $\\beta_1$ (population parameter for the slope) because once we know $\\beta_0$ and $\\beta_1$, we know the exact shape of $f$ and we know the relationship of $y$ and $x$, and given any value of $x$, we can predict its corresponding value of $y$ using the regression line $\\hat{y}_{i} = \\beta_0 + \\beta_1~x_{i}$.\n- But again the population parameters are unknown to us.\n- $\\hat{y}_i = E(Y|X_i=x_i)$\n- $b_0$: intercept of the sample regression line\n- $b_1$: slope of  the sample regression line\n\n:::\n\n\n## Fitting a Regression Line $\\hat{Y} = b_0 + b_1X$\n\nGiven the data $\\{ (x_1, y_1), (x_2, y_2), \\dots, (x_n, y_n)\\},$\n\n- Which *sample* regression line is the **best**? \n- Which estimates $b_0$ and $b_1$ provide the **best-fitting** line?\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-8-1.png){fig-align='center' width=58%}\n:::\n:::\n\n\n\n::: notes\n- Now suppose we already get our sample, and now we are trying to use the sample to get a sample regression line, and hopefully, the sample regression line and the population regression line are alike. look similarly.\n- So people usually ask\n- Which *sample* regression line is the **best**? \n- What are the **best** estimators $b_0$ and $b_1$ for $\\beta_0$ and $\\beta_1$?\n- After all, given the data, we can generate so many different straight lines, and we need a criterion to help us determine which line is the best in some sense. Right!\n:::\n\n\n\n## MPG Data\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: notes\n\nThat's see the idea of Ordinary Least Squares visually. Here just showed the data.\n- Later we will work on the data set together.\n<!-- - Do you see why some points are darker than some others? -->\n<!-- - A darker point means that there are several identical (x, y) pairs, or replicates in the data set. -->\n\n:::\n\n\n## Fitted Line and Fitted Value\n\n$\\hat{y}_i = c_0 + c_1x_i$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: notes\n\n- All right, with the data, this figure also shows the least squares regression line, and the fitted value of $y$ for each $x$ in the training data, which are those red points.\n- The fitted values of y are right on the regression line.\n- Now the question is, how do we find this line?\n- Given a line, we can have predicted values of y, right?\n- Then what is residual on the plot? The residual will be the difference between the true observation y and the fitted value of y given any value of x.\n- So a residual in the plot will be a vertical bar at the value of x with two ends of the bar $y$ and $\\hat{y}$, right?\n- (Show on board)\n- (add $y_i = b_0+b_1x_i$ and residual line)\n\n:::\n\n\n## Residuals\n\n- A **residual** is the difference between the observed response and the fitted response value, shown as a vertical bar.\n\n- $e_i = y_i - \\hat{y}_i$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: notes\n\n- Here shows all the residuals in vertical bars.\n- least squares line is the line such that the sum of all the squared residuals is minimized.\n- Why we square the residuals? \n- It's mathematically more convenient.\n- Squaring emphasizes larger differences\n\n:::\n\n\n## What does \"best\" mean? Ordinary Least Squares (OLS)\n\n\nChoose $b_0$ and $b_1$—and therefore the sample regression line—to minimize the **sum of squared residuals** $$SS_{res} = e_1^2 + e_2^2 + \\dots + e_n^2 = \\sum_{i = 1}^n e_i^2.$$\n\n\n<!-- Choose the *best* $b_0$ and $b_1$ or the sample regression line minimizing the **sum of squared residuals** $$SS_{res} = e_1^2 + e_2^2 + \\dots + e_n^2 = \\sum_{i = 1}^n e_i^2.$$ -->\n\n. . .\n\n- Substituting $e_i=y_i-(b_0+b_1x_i)$ into $SS_{res}$ gives\n\n$$\\begin{align} SS_{res}(b_0, b_1) &= (y_1 - b_0 - b_1x_1)^2 + (y_2 - b_0 - b_1x_2)^2 + \\dots + (y_n - b_0 - b_1x_n)^2\\\\ &= \\sum_{i=1}^n(y_i - b_0 - b_1x_i)^2 \\end{align}$$ \n\n\n- The resulting value is no larger than $\\sum_{i=1}^n(y_i-a_0-a_1x_i)^2$ for any other pair $(a_0,a_1)\\ne(b_0,b_1)$.\n\n<!-- that is the smallest comparing to any other $\\sum_{i=1}^n(y_i - a_0 - a_1x_i)^2$ that uses another pair of estimators $(a_0, a_1) \\ne (b_0, b_1)$. -->\n\n\n\n::: notes\n\n- Now the question is How do we get $b_0$ and $b_1$ that well estimate $\\beta_0$ and $\\beta_1$? \n- We choose $b_0$ and $b_1$, or regression line $b_0 + b_1x$ that minimizes the **sum of squared residuals**.\n- If we define residual as $e_i = y_i - \\hat{y}_i$, then the sum of squared residuals is $\\sum_{i = 1}^n e_i^2$.\n- And this approach that estimates the population parameters $\\beta_0$ and $\\beta_1$ or the population regression line is called Ordinary Least Squares method.\n\n:::\n\n\n## \n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**The Least-Squares (Best) Line**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n**A Non-optimal Line**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Least Squares Estimates\n\n- The least-squares approach chooses $b_0$ and $b_1$ to minimize $SS_{res}$:\n$$(b_0, b_1) = \\arg\\min_{\\alpha_0, \\alpha_1} \\sum_{i=1}^n(y_i - \\alpha_0 - \\alpha_1x_i)^2$$\n. . .\n\n$$ \\color{red}{b_0 = \\overline{y} - b_1\\overline{x}}$$\n\n\n$$\\color{red}{b_1 = \\frac{\\sum_{i=1}^n(x_i - \\overline{x})(y_i - \\overline{y})}{\\sum_{i=1}^n(x_i - \\overline{x})^2} = \\frac{S_{xy}}{S_{xx}} = r \\frac{\\sqrt{S_{yy}}}{\\sqrt{S_{xx}}}},$$ where $S_{xx} = \\sum_{i=1}^n(x_i - \\overline{x})^2$, $S_{yy} = \\sum_{i=1}^n(y_i - \\overline{y})^2$, $S_{xy} = \\sum_{i=1}^n(x_i - \\overline{x})(y_i - \\overline{y})$, and $r$ is the sample correlation coefficient between $x$ and $y$.\n\n. . .\n\n::: question\nWhat can we learn from the formulas for $b_0$ and $b_1$?\n:::\n\n\n::: notes\n- The LS regression line passes through the centroid.\n- $b_1$ is kinda like a scaled covariance of X and Y.\n- $b_0$ and $b_1$ are correlated.\n:::\n\n\n## Why squared residuals matter {visibility=\"hidden\"}\n\n| Residual | Absolute error | Squared error | Consequence |\n|---:|---:|---:|---|\n| 1 | 1 | 1 | small penalty |\n| 2 | 2 | 4 | larger penalty |\n| 5 | 5 | 25 | very large penalty |\n| 10 | 10 | 100 | can dominate the fit |\n\n\n::: {.fragment}\n\n**Least squares is sensitive to large residuals.** That is useful when large errors really matter, dangerous when they are mistakes or special cases.\n\n:::\n\n## Formula, but only the useful version {visibility=\"hidden\"}\n\n$$\n(b_0,b_1)=\\arg\\min_{a,b}\\sum_{i=1}^{n}(y_i-a-bx_i)^2\n$$\n\n::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| Quantity | Interpretation |\n|---|---|\n| $b_1$ | estimated change in mean $Y$ per 1-unit increase in $X$ |\n| $b_0$ | estimated mean $Y$ when $X=0$ |\n| $\\hat y_i$ | fitted mean at $x_i$ |\n| $e_i$ | remaining error after using the line |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Key point:** fitting is not the hard part. The hard part is deciding whether the fitted line answers the question.\n\n:::\n:::\n\n\n## Fitting\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n(reg_fit <- lm(formula = hwy ~ displ, data = mpg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hwy ~ displ, data = mpg)\n\nCoefficients:\n(Intercept)        displ  \n      35.70        -3.53  \n```\n\n\n:::\n:::\n\n\n. . .\n\n- $\\widehat{hwy}_{i} = b_0 + b_1 \\times displ_{i} =  35.7  - 3.5 \\times displ_{i}$\n\n<!-- - $b_1$: For one unit (litre) increase of the displacement, we expect the highway MPG to be decreased, [on average]{.red}, by 3.5 miles. -->\n\n- $b_1$: For each one-liter increase in engine displacement, expected highway fuel economy decreases by 3.5 MPG, [on average]{.red}.\n\n. . .\n\n::: question\n\nIs the intercept meaningful here?\n\n:::\n\n\n## What did we estimate in the MPG example? {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                | estimate|meaning                                                          |\n|:-------------------|--------:|:----------------------------------------------------------------|\n|Intercept           |    35.70|Predicted highway MPG at 0 liters; not substantively useful here |\n|Engine displacement |    -3.53|Change in expected highway MPG for +1 liter displacement         |\n\n\n:::\n:::\n\n\n## Slope Interpretation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\ncoef(reg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       displ \n      35.70       -3.53 \n```\n\n\n:::\n:::\n\n\n| Component | MPG example |\n|---|---|\n| Direction | larger engines have lower predicted highway MPG |\n| Magnitude | about -3.53 MPG per additional liter |\n| Units | MPG per liter |\n| Population | car models like those in `ggplot2::mpg` |\n| Range | mainly within observed displacement values |\n| Causal language? | not justified from this dataset alone |\n\n\n\n## Centering Makes the Intercept Meaningful\n\n<!-- Raw model: -->\n\n<!-- $$ -->\n<!-- \\widehat{hwy}=b_0+b_1\\,displ -->\n<!-- $$ -->\n\n<!-- . . . -->\n\nCentered model:\n\n$$\n\\widehat{hwy}=c_0+c_1(displ-\\overline{displ})\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-line-numbers=\"false\"}\nmpg_data <- ggplot2::mpg |>\n  filter(!is.na(displ), !is.na(hwy)) |>\n  mutate(displ_c = displ - mean(displ))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n(fit_mpg_c <- lm(hwy ~ displ_c, data = mpg_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hwy ~ displ_c, data = mpg_data)\n\nCoefficients:\n(Intercept)      displ_c  \n      23.44        -3.53  \n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|model    | intercept| slope|intercept meaning                                                                       |\n|:--------|---------:|-----:|:---------------------------------------------------------------------------------------|\n|Raw      |      35.7| -3.53|predicted MPG at 0 liters                                                               |\n|Centered |      23.4| -3.53|predicted MPG at <span style=\"     color: red !important;\" >average</span> displacement |\n\n\n:::\n:::\n\n\n\n## Comparisons are Regressions\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/transmission-comparison-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Categorical Predictor with 2 Categories\n\n**Question**: [How do automatic and manual transmissions differ in highway MPG?]{.blue}\n\n:::: {.columns}\n\n::: {.column width=\"31%\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nmpg |>  \n  select(hwy, trans) |>  \n  print(n = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 234 × 2\n    hwy trans     \n  <int> <chr>     \n1    29 auto(l5)  \n2    29 manual(m5)\n3    31 manual(m6)\n4    30 auto(av)  \n# ℹ 230 more rows\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n::: {.column width=\"69%\"}\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nmpg_new <- mpg\nmpg_new$trans[grepl(\"auto\", mpg_new$trans)] <- \"auto\"\nmpg_new$trans[grepl(\"manual\", mpg_new$trans)] <- \"manual\"\n\nmpg_new |> \n    select(hwy, trans) |> \n    print(n = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 234 × 2\n    hwy trans \n  <int> <chr> \n1    29 auto  \n2    29 manual\n3    31 manual\n4    30 auto  \n# ℹ 230 more rows\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n::::\n\n. . .\n\n- `trans = auto`: automatic transmission\n- `trans = manual`: manual transmission\n\n\n## Indicator Variables\n\nDefine a binary indicator variable:\n\n$$\nx_i =\n\\begin{cases}\n0, & \\text{automatic},\\\\\n1, & \\text{manual}.\n\\end{cases}\n$$\n\nThe regression model is\n\n$$\nhwy_i = \\beta_0+\\beta_1x_i+\\epsilon_i.\n$$\n\n| Coefficient | Meaning |\n|---|---|\n| $\\beta_0$ | Mean highway MPG for automatic transmission |\n| $\\beta_1$ | Manual mean minus automatic mean |\n| $\\beta_0+\\beta_1$ | Mean highway MPG for manual transmission |\n\n\n. . .\n\nThe fitted regression model is\n\n$$\n\\widehat{hwy}_i = b_0+b_1 x_i\n$$\n\n\n\n::: notes\n\n- A regression predictor does not have to be quantitative.\n- Transmission type has two categories: automatic and manual.\n- We represent transmission type using an indicator variable.\n- Automatic transmission is the reference category and is assigned a value of zero.\n- Manual transmission is assigned a value of one.\n- The regression coefficient beta one is therefore a difference between two group means.\n- This illustrates an important general idea: a comparison between two groups can be written as a regression model.\n\n:::\n\n\n## The Slope is a Mean Difference\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\ntrans_fit <- lm(hwy ~ trans, data = mpg_new)\ncoef(trans_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) transmanual \n      22.29        3.49 \n```\n\n\n:::\n:::\n\n\n::: center\n\n$\\widehat{hwy}_i = 22.29+3.49 x_i$\n\n:::\n  \n<!-- The fitted regression model is -->\n\n<!-- $$ -->\n<!-- \\widehat{hwy}_i -->\n<!-- = -->\n<!-- 22.29 -->\n<!-- + -->\n<!-- 3.49M_i. -->\n<!-- $$ -->\n\n. . .\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n### Auto $x_i=0$\n\n$$\n\\begin{aligned}\n\\widehat{hwy}_{\\text{auto}}\n&=\n22.29\n+\n3.49(0)\\\\\n&=\n22.29\n\\text{ MPG}\n\\end{aligned}\n$$\n\n**$b_0$ is the mean highway MPG for the [reference (baseline)]{.red} category.**\n\n:::\n\n::: {.column width=\"50%\"}\n\n### Manual $x_i=1$\n\n$$\n\\begin{aligned}\n\\widehat{hwy}_{\\text{manual}}\n&=\n22.29\n+\n3.49(1)\\\\\n&=\n25.78\n\\text{ MPG}\n\\end{aligned}\n$$\n\n**$b_0+b_1$ is the mean highway MPG for [manual]{.red} transmission.**\n\n:::\n\n::::\n\n::: {.fragment}\n\n<!-- $$ -->\n<!-- \\underbrace{ -->\n<!-- 25.78 -->\n<!-- }_{\\text{manual mean}} -->\n<!-- - -->\n<!-- \\underbrace{ -->\n<!-- 22.29 -->\n<!-- }_{\\text{automatic mean}} -->\n<!-- = -->\n<!-- \\underbrace{ -->\n<!-- 3.49 -->\n<!-- }_{\\text{regression coefficient}} -->\n<!-- $$ -->\n\n- **Slope:** Cars with manual transmissions are expected to have 3.49 MPG higher highway fuel economy, on average, than cars with automatic transmissions.\n  + The coefficient compares the other level (`trans = manual`) with the baseline (`trans = auto`).\n\n\n:::\n\n::: notes\n\n- When the indicator variable equals zero, the fitted value equals the intercept.\n- Therefore, the intercept is the mean highway MPG for automatic-transmission configurations.\n- When the indicator variable equals one, the fitted value is the intercept plus the manual-transmission coefficient.\n- The slope is exactly the difference between the two group means.\n- We should interpret this as an observed comparison or association, not as a causal effect.\n- The data do not establish that changing a vehicle from automatic to manual transmission would cause highway MPG to increase by this amount.\n- Automatic and manual vehicle configurations can also differ in engine displacement, vehicle class, manufacturer, and other characteristics.\n\n:::\n\n\n##\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/transmission-comparison-reg-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Estimation for $\\sigma^2$\n\n- Think of $\\sigma^2$ as the **variance around the population regression line**.\n\n- The estimate of $\\sigma^2$, denoted by $s^2$ or $\\hat{\\sigma}^2$, is computed from the data as\n$$s^2 = \\frac{SS_{res}}{df_{res}} = \\frac{\\sum_{i=1}^n(y_i - \\hat{y}_i)^2}{n-2} = MS_{res}$$\n\n<!-- - Think of $\\sigma^2$ as **variance around the line** or the **mean squared error**. -->\n\n<!-- - The estimate of $\\sigma^2$, denoted as $s^2$ or $\\hat{\\sigma}^$, computed from the data is  -->\n<!-- $$s^2 = \\frac{SS_{res}}{df_{res}} = \\frac{\\sum_{i=1}^n(y_i - \\hat{y}_i)^2}{n-2} = MS_{res}$$ -->\n\n<!-- - $s$: the **residual standard error** or **standard error of regression**, is a measure of the *lack of fit* of the regression model to the data. -->\n\n- $s$, the **residual standard error**, estimates the typical vertical distance between an observed response and the fitted line.\n\n\n. . .\n\n\n::: {.cell layout-align=\"center\" output.lines='[15,16]'}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n(summ_reg_fit <- summary(reg_fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n...\n\nResidual standard error: 3.84 on 232 degrees of freedom\n...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nsumm_reg_fit$sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.84\n```\n\n\n:::\n:::\n\n\n\n::: notes\n\n- So we are done estimation for $beta$. Let's talk about the estimation of $\\sigma^2$.\n- The estimate of $\\sigma^2$, denoted as $s^2$ or $s_{\\epsilon}^2$, based on the sample data is residual sum of squares divided by $n-2$, the degrees of freedom\n- It can be shown that $E(SS_{res}) = (n-2)\\sigma^2$. That is, $s^2$ is an *unbiased* estimator for $\\sigma^2$. 👍\n- measure of the *lack of fit* of the regression model to the data.\n\n:::\n\n\n\n## Measure of the *Lack of Fit*\n\n- If $\\hat{y}_i \\approx y_i$, then $s$ will be small, and the model fits the data well.\n\n<!-- - If $\\hat{y}_i$ is far away from $y_i$, $s$ may be large, indicating the model does not fit the data well.  -->\n\n- If many fitted values $\\hat y_i$ are far from the observed responses $y_i$, then $s$ will be large, indicating substantial unexplained variation or model misspecification.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-24-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::: notes\n\n- If the fitted value using the model is close to the true value, $\\hat{y}_i \\approx y_i$, then $s$ will be small, and the model fits the data well. \n- If $\\hat{y}_i$ is far away from $y_i$, $s$ may be large, indicating that the model does not fit the data well. \n- Let's see the example shown below. If X and Y have a linear relationship and the relationship is pretty tight, we should see the fitted values on the fitted line are close to the observations, and the $s$ will be small.\n- But if X and Y have a quadratic relationship, but we fit a linear regression, the fitted values will be distant from the observations, and $s$ may be large.\n- The case on the right shows the violation of constant variance. In this case, the fitted values are away from the observations too, resulting in large $s$, and indicating the model does not fit the data well. OK.\n\n:::\n\n\n\n\n# Uncertainty Quantification \n\n\n\n## Sampling Variation\n\n- Our data are **one realization** among many possible data sets generated by a true data-generating process described by a regression model.\n\n- **[Repeated Sampling]** If we collected another data set, we would obtain a different pair $(b_0, b_1)$.\n\n- Suppose the true model is $Y_i = 5 + 2X_i + \\epsilon_i$, $\\epsilon_i \\stackrel{iid}{\\sim} N(0, 25)$\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: center\n$(b_0, b_1) = (4.67, 2.05)$\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-26-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n::: fragment\n\n::: center\n$(b_0, b_1) = (3.56, 2.48)$\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n:::\n\n::::\n\n\n## Sampling Variation\n\n- We quantify the sampling variation of $(b_0,b_1)$ to assess the uncertainty in using them to estimate $(\\beta_0,\\beta_1)$.\n\n- If $\\epsilon_i\\stackrel{iid}{\\sim}N(0,\\sigma^2)$, we can derive the exact sampling distributions of $b_0$ and $b_1$.[^1]\n\n[^1]: We can also derive an exact sampling distribution for an estimator of $\\sigma^2$. The framework used in this course for inference, prediction, and uncertainty quantification is the **frequentist** approach.\n\n. . . \n\nThese sampling distributions yield confidence intervals (CIs) for $\\beta_0$ and $\\beta_1$:\n\n- A $(1-\\alpha)100\\%$ CI for $\\beta_1$ is $\\small \\boxed{b_1\\pm t_{\\alpha/2,\\,n-2}\\,se(b_1)}$, where $se(b_1)$ is the standard error of $b_1$.\n\n- A 95% CI for $\\beta_1$ is approximately $\\small \\boxed{b_1\\pm2\\,se(b_1)}$.\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nconfint(reg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5 % 97.5 %\n(Intercept) 34.28  37.12\ndispl       -3.91  -3.15\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: danger\n\nWe would never know whether the CI covers the true parameter values or not.\n\n:::\n\n\n::: notes\n\nsumm_reg_fit$coefficients\n\n:::\n\n<!-- # Learning from Simulation -->\n\n\n\n<!-- ## Fake-data simulation workflow -->\n\n<!-- | Step | What we do | Why | -->\n<!-- |---|---|---| -->\n<!-- | 1 | Choose a known data-generating model | truth is known | -->\n<!-- | 2 | Simulate many datasets | see sample-to-sample variation | -->\n<!-- | 3 | Fit the same regression each time | test the workflow | -->\n<!-- | 4 | Compare estimates to truth | learn what uncertainty means | -->\n\n\n\n\n## Generating Sampling Distribution from Simulation\n\n\n::: {.instructions}\n\n**Algorithm**  \n\n- [Create the pretend world]{.blue}\n  + A true regression model\n  \n- [Repeat sampling $M$ times]{.blue}\n  + Generate $M$ data sets of size $n$ from the true model: $D^1, \\dots, D^M$\n\n- [Fit the model $M$ times]{.blue}\n  + For each data set $D^m, m = 1, \\dots, M$, compute the estimate $b_1^m$ and confidence intervals $CI^m$\n\n- [Quantify uncertainty]{.blue}\n  + Plot a histogram of the $M$ estimates $b_1^1, \\dots, b_1^M$ to visualize sampling variation\n  + Compute the percentage of confidence intervals that contain the true value\n\n:::\n\n\n\n<!-- ::: algo -->\n\n\n<!-- - Create the pretend world  -->\n<!--  + Set the true regression model -->\n\n<!-- - Simulate  -->\n\n\n<!-- ::: -->\n\n\n\n<!-- ## Same Truth, Different Data -->\n\n##\n\n- True model: $Y_i = 5 + 2X_i + \\epsilon_i$, $\\epsilon_i \\stackrel{iid}{\\sim} N(0, 25)$\n\n- Generate $M=100$ simulated data sets, each of size $n=50$.\n\n- Each data set produces a different pair $(b_0,b_1)$.\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/fake-lines-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Sampling Variation of the Slope\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/slope-sim-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Coverage Probabilities\n\n- $\\text{Empirical coverage}=\\dfrac{\\text{number of CIs containing }\\beta_1}{M}$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n## What uncertainty is trying to say {visibility=\"hidden\"}\n\n::: danger\n\n\n| Output | Better interpretation | Common misuse |\n|---|---|---|\n| Estimate | best single-number summary from this data/model | the truth |\n| Standard error | typical estimation noise | measurement error of $Y$ |\n| Confidence interval | plausible values under the model | probability the fixed parameter is in this one interval |\n| p-value | incompatibility with a point null | probability the null is true |\n\n\n:::\n\n\n<!-- # Inference without overemphasizing tests -->\n\n## Testing the slope: what the test can and cannot say {visibility=\"hidden\"}\n\n| Result | What it supports | What it does not prove |\n|---|---|---|\n| small p-value | data are not very compatible with zero slope under the model | the relationship is linear |\n| large p-value | slope is not precisely distinguished from zero | no relationship exists |\n| narrow interval | slope is estimated precisely | model assumptions are correct |\n| wide interval | data are not very informative | the effect is unimportant |\n\n\n\n## Hypothesis Testing\n\n- <span style=\"color:blue\"> $H_0: \\beta_1 = \\beta_1^0 \\quad H_1: \\beta_1 \\ne \\beta_1^0$  </span>\n\n- Under $H_0$, the test statistic is $t_{test}=\\dfrac{b_1-\\color{red}{\\beta_1^0}}{se(b_1)}\\sim t_{n-2}$.\n\n- Reject $H_0$ in favor of $H_1$ if \n  + $|t_{test}| > t_{\\alpha/2, \\, n-2}$ (critical value method)\n  + $\\text{p-value} = 2P(t_{n-2} > |t_{test}|) < \\alpha$ (p-value method)\n \n. . .\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nsumm_reg_fit$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value  Pr(>|t|)\n(Intercept)    35.70      0.720    49.6 2.12e-125\ndispl          -3.53      0.195   -18.2  2.04e-46\n```\n\n\n:::\n:::\n\n\n- By default, `summary()` tests $H_0:\\beta_0=0$ and $H_0:\\beta_1=0$.\n\n::: notes\n- in addition to estimation, we may be interested in testing.\n- To do the testing on $\\beta_1$, the testing procedure is basically the same as the procedure for population mean $\\mu$ we reviewed last week.\n- Usually $\\beta_1^0 = 0$, but we may be interested in other values.\n- good growth $\\beta_1 > 2$\ncar::linearHypothesis()\n:::\n\n\n\n## Interpretation of Testing Results\n\n- <span style=\"color:blue\"> $H_0: \\beta_1 = 0 \\quad H_1: \\beta_1 \\ne 0$ </span>\n- *Failing to reject $H_0: \\beta_1 = 0$* (large p-value) means that the slope is not estimated precisely enough to distinguish it from zero.\n  + It does not mean the slope is exactly zero\n  + It does not *prove* that no linear relationship exists\n  + A nonlinear relationship may still exist.\n\n\n::: notes\n\n- So back to the testing on $\\beta_1$.\n- If we do not reject $H_0$, it implies there is **no linear relationship** between $Y$ and $X$. Right? Because $\\beta_1$, the slope of the regression line is pretty much 0. \n:::\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-33-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n::: notes\n- But it actually has two cases. One $x$ and $y$ may have no relationship at all, or they don't have linear relationship but have another kind of relationship, like quadratic.\n- So we have to be careful when we interpret the testing result. OK.\n:::\n\n::: notes\nWe have to be more careful and precise on what we are claiming.\n:::\n\n\n\n## Interpretation of Testing Results\n\n- *Rejecting $H_0: \\beta_1 = 0$* (small p-value) means that the data are not very compatible with a zero slope under the model.\n\n- The result is consistent with several possibilities:\n  + the straight-line model may be adequate\n  + it does not prove that the relationship is linear\n  + another model may describe the relationship better\n  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-34-1.png){fig-align='center' width=45%}\n:::\n:::\n\n\n\n::: notes\n\n- *Rejecting $H_0: \\beta_1 = 0$* (small p-value) means data are not very compatible with zero slope under the model.\n\n- It could mean \n  + the straight-line model is adequate\n  + it does not prove the relationship is linear\n  + better results could be obtained with a more complicated model even though there is a linear effect of $x$ , even though the fitted linear slope differs from zero.\n  \n  \n:::\n\n\n\n# Prediction\n\n## Fitting and Predicting\n\n- **Fitting** uses the observed data to estimate a model.\n\n- **Prediction** applies the fitted model to unseen data.\n  + We use the model to predict a response at a new predictor value $x^{new}$.\n\n. . .\n\n- Two prediction targets:\n\n  + **Mean response:** <span style=\"color:blue\">The **mean** highway MPG, $E(Y\\mid X=x^{new})$, for cars with $x^{new}=3$ liters of displacement.</span>\n  \n  + **New observation:** <span style=\"color:blue\">The highway MPG, $Y^{new}$, of **one future car** with $x^{new}=3$ liters of displacement.</span>\n  \n::: question\nWhich prediction is harder? 🤔\n:::\n  \n## Point Prediction\n\n- The fitted value on the regression line is the point prediction for both the mean response and a new observation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\npredict(reg_fit, newdata = data.frame(displ = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   1 \n25.1 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-36-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: notes\n| Target | Question | Usually shown as |\n|---|---|---|\n| Fitted value | What does the fitted line say at $x_0$? | point on line |\n| Mean response | What is the average $Y$ among units with $X=x_0$? | confidence interval/band |\n| New observation | What might one future $Y$ be at $X=x_0$? | prediction interval/band |\n:::\n\n\n## Predictive Uncertainty\n\n<!-- - **Mean response**: The *linear predictor* $\\beta_0 + \\beta_1x^{new}$ propagates the inferential uncertainty in $(\\beta_0, \\beta_1)$. -->\n<!--   + represents the distribution of uncertainty about the expected or average value of $y$ for new data points with predictors $x^{new}$ -->\n\n<!-- - **New observation**: The predictive distribution for a new observation, $\\beta_0 + \\beta_1x^{new} + \\epsilon$: -->\n<!--   + represents uncertainty about a new observation $y^{new}$ with predictors $x^{new}$ -->\n\n\n- **Mean response:** Uncertainty arises because $\\beta_0$ and $\\beta_1$ are estimated from a sample.\n  + It quantifies uncertainty about the expected response $E(Y\\mid X=x^{new}) = \\beta_0 + \\beta_1x^{new}$.\n  \n- **New observation:** The predictive distribution includes both parameter-estimation uncertainty and a new random error $\\epsilon$, $\\beta_0 + \\beta_1x^{new} + \\epsilon$.\n  + It quantifies uncertainty about one future response $Y^{new}$ at $x^{new}$.\n\n\n\n. . .\n\n::: question\nWhich uncertainty is larger? 🤔\n:::\n  \n. . .\n\n::: danger\n\n- As sample size approaches infinity, $\\beta_0$ and $\\beta_1$ are estimated more and more precisely, and the uncertainty in the linear predictor approaches zero.\n\n- Uncertainty for a new observation does not approach zero; it approaches irreducible error standard deviation $\\sigma$.\n\n:::\n\n\n## Interval Prediction\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nWith $\\epsilon_i \\stackrel{iid}{\\sim} N(0, \\sigma^2)$, we have\n\n- The $(1-\\alpha)100\\%$ CI for $E(y\\mid x^{new})$ is $$\\small (b_0+b_1x^{new}) \\pm t_{\\alpha/2, n-2} S\\sqrt{\\frac{1}{n} + \\frac{(x^{new} - \\overline{x})^2}{S_{xx}}}$$\n\n- The $(1-\\alpha)100\\%$ **prediction interval** (PI) for $y(x^{new})$ is $$\\small (b_0+b_1x^{new}) \\pm t_{\\alpha/2, n-2} S\\sqrt{ {\\color{red}{1}} + \\frac{1}{n} + \\frac{(x^{new} - \\overline{x})^2}{S_{xx}}}$$\n\n::: fragment\n\n- *The PI is wider because it includes uncertainty about $\\beta_0$ and $\\beta_1$ as well as the random error $\\epsilon$*.\n\n:::\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n::: fragment\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n## CI for the mean response\npredict(reg_fit, \n        newdata = data.frame(displ = 3), \n        interval = \"confidence\", \n        level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 25.1 24.6 25.6\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\n## PI for a new observation\npredict(reg_fit, \n        newdata = data.frame(displ = 3), \n        interval = \"prediction\", \n        level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 25.1 17.5 32.7\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n::::\n\n\n\n\n## Confidence Interval vs. Prediction Interval\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-39-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Confidence Interval vs. Prediction Interval\n\nThe interval is shortest when $x^{new} = \\bar{x}$!\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-40-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Interpolation vs extrapolation {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/extrapolation-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## {background-iframe=\"https://chenghanyustats-introstat-regression-ci.share.connect.posit.cloud/\" background-interactive=\"true\"}\n\n\n## Prediction requires available predictors {visibility=\"hidden\"}\n\n| Predictor type | Safe for future prediction? | Example |\n|---|---|---|\n| measured before prediction time | usually yes | engine displacement |\n| measured after the outcome | no | final exam score to predict course grade |\n| derived using the outcome | no | rank computed after observing $Y$ |\n| forecasted predictor | maybe | economic growth forecast for election prediction |\n\n\n\n# Model Checking\n\n## A Fitted Line Can Miss Curvature\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/nonlinear-miss-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Residuals: what remains after the line?  {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/residual-plot-mpg-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Graphical Diagnostics: Residual Plot\n\n- Residuals should be distributed randomly around 0.\n- Check this by plotting residuals against the fitted value of $y$: $e_i$ vs. $\\hat{y}_i$\n- Look for a roughly horizontal band with no systematic pattern.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-41-1.png){fig-align='center' width=56%}\n:::\n:::\n\n\n::: notes\nWe are looking for\n- Residuals distributed randomly around 0.\n- With no visible pattern along the $x$ or $y$ axes.\n- This can be checked by plotting residuals against the fitted value of $y$.\n- Here shows a good residual plot. Residuals are around 0, and its variation is more or less the same across different values of $\\hat{y}$.\n- There is no significant pattern in the plot.\n:::\n\n## Residual Pattern Reveals the Miss\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/nonlinear-resid-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Not looking for...\n\n:::{.large}\n**Fan shapes**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-42-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n::: notes\n- We are not looking for a plot that has a fan shape.\n:::\n\n\n\n## Not looking for...\n\n:::{.large}\n**Distinct groups or clusters**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-43-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n::: notes\n- We are not looking for a plot that has **Groups of patterns**\n:::\n\n\n\n## Not looking for...\n\n:::{.large}\n**Residuals correlated with predicted values**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-44-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n::: notes\n- We also don't want Residuals to be correlated with predicted values\n:::\n\n\n\n## Not looking for...\n\n:::{.large}\n**Any patterns!**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-45-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n::: notes\n- We basically don't want the residuals show Any patterns!\n- If $X$ and $Y$ are not linearly related, or the residual plot exists some pattern, some data transformation is needed. Or use another model.\n:::\n\n\n\n## MPG Data Residuals\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nplot(reg_fit, which = 1, col = \"blue\", las = 1)\n```\n\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-46-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n## Nonconstant Variance Changes Uncertainty  {visibility=\"hidden\"}\n\n<!-- # ```{r} -->\n<!-- # #| label: heteroskedastic -->\n<!-- # set.seed(480) -->\n<!-- # het_dat <- tibble(x = runif(180, 0, 10)) |> -->\n<!-- #   mutate(y = 5 + 2 * x + rnorm(n(), 0, 0.5 + 0.45 * x)) -->\n<!-- # fit_het <- lm(y ~ x, data = het_dat) -->\n<!-- # het_aug <- het_dat |> -->\n<!-- #   mutate(fitted = fitted(fit_het), resid = resid(fit_het)) -->\n<!-- #  -->\n<!-- # ggplot(het_aug, aes(fitted, resid)) + -->\n<!-- #   geom_hline(yintercept = 0, linewidth = 1) + -->\n<!-- #   geom_point(alpha = 0.55, size = 2.1) + -->\n<!-- #   labs( -->\n<!-- #     title = \"Fan-shaped residuals suggest changing variability\", -->\n<!-- #     x = \"Fitted value\", -->\n<!-- #     y = \"Residual\" -->\n<!-- #   ) -->\n<!-- # ``` -->\n\n\n# Considerations in the Usage of Regression\n\n\n\n## Considerations in Regression: Extrapolation\n\n- Regression models are most reliable for **interpolation** within *the range of predictor values* used to fit the model.\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-47-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-48-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n\n::: notes\n\n- First, Regression models are intended as **interpolation** equations over the range of the regressors used to fit the model.\n- Regression does a really bad job for extrapolation. \n- Look at this figure for example.\n- Suppose the data we collected have the range of X like this.\n- Based on the data, we train our model, and estimate the parameters for prediction and inference.\n- Our prediction and inference will be more plausible or convicing when the new $x$ is within the range of $X$.\n- Again, the only information we have is our data. \n- When we do extrapolation, it's like doing a prediction or inference without any reliable information at hand.\n- Our conclusion may be totally wrong. Based on the collected data, we thought x and y are linear related.\n- But the true x-y relationship may not be linear at all, and because our data only cover a small range of $X$, we don't know what really happens outside the range of data. \n- We cannot say much about the predictive mean response or observation outside the range of $X$, and we cannot conclude the relationship between x and y outside the range as well.\n\n:::\n\n\n## Considerations in the Use of Regression: Outliers\n\n- **Outlier**: An observation with an *unusual response value* relative to other observations, especially given its $x$ value.\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-49-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n\n\n::: {.column width=\"50%\"}\n\n- The estimated coefficients may change substantially.\n\n- The residual mean square may be inflated.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nsummary(lm_outlier)$sigma ^ 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1421\n```\n\n\n:::\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nsummary(lm_no_outlier)$sigma ^ 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 101\n```\n\n\n:::\n:::\n\n\n:::\n\n::::\n\n\n\n::: notes\n\n- The second consideration is outlier.\n- it might be just measurement error.\n- If it is not an typo, we have to look into this point with great care, and see why this happened and see if we need to do some correction to it.\n- We will talk about outliers in detail later in this course.\n\n:::\n\n\n\n## Considerations in Regression: Influential Points {.nostretch}\n\n- **Influential point**: An observation whose inclusion substantially *changes the fitted regression results*; it often has an *unusual $x$ value.*\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-51-1.png){fig-align='center' width=65%}\n:::\n:::\n\n\n\n::: notes\n\n- Our inference and prediction may be totally distorted just because of one single influential point. So again, we have to very careful about it.\n\n:::\n\n\n## Considerations in Regression: Causal Interpretation?\n<!-- - Correlation is NOT Causation! -->\n<!-- - Remember this when interpreting model coefficients! -->\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/icecream.jpeg){fig-align='center' width=56%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-53-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::\n\n\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/drowning.jpeg){fig-align='center' width=56%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/unnamed-chunk-55-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::\n\n::::\n\n::: notes\n\n- Regression is just a model. It does not tell you X-Y's relationship is correlation relationship or causal relationship. \n- It is the person who uses the model tell the relationship.\n- So we have to be careful when interpreting regression result.\n- They are correlated, not one causes the other.\n- Actually, there is another factor that causes the sales and # of drownings to go up and down together.\n\n:::\n\n\n## Considerations in Regression: Unknown Predictor\n\n- Consider maximum daily electrical load $(Y)$ and maximum daily temperature $(X)$.\n\n- To predict tomorrow's maximum load, we must first know or forecast tomorrow's maximum temperature.\n\n- The load prediction is therefore **conditional** on the temperature forecast.\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/electricity.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/electricity_snow.jpeg){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n\n## Outlier, leverage, influence  {visibility=\"hidden\"}\n\n| Term | Plain meaning | Main question |\n|---|---|---|\n| Outlier | unusual $Y$ given its $X$ | does the model miss this case? |\n| High leverage | unusual $X$ value | can this point pull the line? |\n| Influential | changes the fitted result | does the conclusion depend on it? |\n\n\n\n## Influence is about what changes  {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/influence-plot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Leave-one-out sensitivity  {visibility=\"hidden\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/leave-one-out-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## $R^2$: useful but limited  {visibility=\"hidden\"}\n\n::: {.columns}\n::: {.column width=\"47%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](./images/04-slr-f26/anscombe-r2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"53%\"}\n\n| $R^2$ says | $R^2$ does not say |\n|---|---|\n| in-sample variance explained | causal validity |\n| fit relative to mean-only model | linearity is adequate |\n| descriptive strength | prediction works on new data |\n| one-number summary | conclusions are robust |\n\n:::\n\n:::\n\n# Interpretation and misuse  {visibility=\"hidden\"}\n\n## Association is not automatically causation  {visibility=\"hidden\"}\n\n| Regression output | Causal interpretation needs |\n|---|---|\n| slope of $Y$ on $X$ | a causal question |\n| adjustment variables | pre-treatment covariates, not post-treatment variables |\n| small p-value | not enough |\n| good prediction | not enough |\n| observational data | design and assumptions about confounding |\n\n\n\n## Regression conclusion template  {visibility=\"hidden\"}\n\n> Among **[population]**, over **[range of X]**, a one-unit increase in **[X]** is associated with an estimated **[change]** in the conditional mean of **[Y]**. The uncertainty interval is **[interval]**. This is **[prediction / description / comparison / causal claim]**, and the main limitations are **[diagnostics / sampling / confounding / extrapolation]**.\n\n## Checklist Before Reporting a Regression Analysis\n\n| Check | Ask this before you report |\n|---|---|\n| Goal | prediction, description, comparison, or causality? |\n| Scale | are units and transformations clear? |\n| Range | interpolation or extrapolation? |\n| Uncertainty | mean response or new observation? |\n| Diagnostics | what pattern remains in residuals? |\n| Sensitivity | do a few observations drive the result? |\n| Causality | what design or assumptions justify causal language? |\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}